traccar/traccar

src/org/traccar/protocol/TeltonikaProtocolDecoder.java
Works only when DIN 1 is connected to ignition and sending of DIN 1 state is enabled
=> Saving Teltonika device power state.

default.cfg, src/org/traccar/ServerManager.java, src/org/traccar/protocol/AutoFon45FrameDecoder.java, src/org/traccar/protocol/AutoFon45ProtocolDecoder.java, test/org/traccar/protocol/AutoFon45ProtocolDecoderTest.java
I was working on it to make Starline M17 device able to send positions to traccar. Basically, protocol is something like previous version of `AutoFon` protocol, but with some significant differences.
I have a question about binary protocols (galileo, autofon, etc.) - their decoder are stateful in fact (stores device identifier after authentication packet received). How traccar supposed to handle multiple devices with same protocol? I guess for now the only way is to start another instance of traccar on a different port.
=> Implemented AutoFon 4.5 protocol (also works for StarLine M10/M11/M16/M17 devices)

pom.xml
Current version 3.1 was failing to start JNDI context with following error:
WARN: Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial - NoInitialContextException (... < WebServer.java:55 < Context.java:125 < Main.java:26 < ...)
This was because of missing JNDI implementation of jetty. In previous version `jetty-all` version was included, which had this implementation included and that's why it was working fine.
Please include it into your codebase to make it compatible with old version of web UI (and my mod in particular).
=> Added jetty-jndi dependency to make old GWT based web UI working

pom.xml, test/org/traccar/web/WebServerInitialContextTest.java
As we discussed yesterday in #1377 I have added a simple smoke test, which will fail if it won't be able to initialise the JNDI context.
Also I have added `jetty.version` property which is re-used in all jetty dependencies definition since now there are four such records in `pom.xml` file.
=> Added smoke test for JNDI context initialisation, in pom.xml jetty version is in property now

src/org/traccar/Context.java, src/org/traccar/database/DataManager.java, src/org/traccar/web/WebServer.java
Implemented three ways to initialise web server as discussed in #1395:
* with new web application ("web.type" = "NEW")
* with old web application ("web.type" = "OLD")
* only api ("web.type" = "API")
Please check and let me know if you have any questions.
=> Initialise API for old interface, added possibility to expose only API

src/org/traccar/Context.java
Right now in `Context.init` method the `connectionManager` initialisation happens before the initialisation of the web application. In the original version it is fine, but in old version (and in my web UI mod) the necessary tables are created by hibernate during web application initialisation. This causes following errors on the first start:
2015-08-31 17:03:44 WARN: Table ‘traccar.positions’ doesn’t exist - MySQLSyntaxErrorException (… < QueryBuilder.java:289 < DataManager.java:349 < ConnectionManager.java:41 < …)
or
2015-08-31 16:48:10  WARN: Table "POSITIONS" not found; SQL statement:
SELECT * FROM positions WHERE id IN (SELECT latestPosition_id FROM devices); [42102-187] - JdbcSQLException (... < QueryBuilder.java:62 < *:132 < DataManager.java:349 < ConnectionManager.java:41 < ...) …
=> Change initialisation order

src/org/traccar/MainEventHandler.java, test/org/traccar/ChannelClosingTest.java
We have a 'gator' device, which uses 'gator' protocol (port 5052). From my understanding in current traccar version (3.1) it is working through UDP protocol (and BTW we don't know how to configure it for TCP, but it's not the case). We were messing with device configuration and received following packets:
````
2015-10-22 00:11:31 DEBUG: [70E792A4: 5052 < 61.245.163.243] HEX: 242421000643e30282070d
2015-10-22 00:11:45 DEBUG: [70E792A4: 5052 < 61.245.163.243] HEX: 242400
2015-10-22 00:11:45  WARN: [70E792A4] error - Not enough readable bytes - Need 2, maximum is 0 - IndexOutOfBoundsException (... < GatorProtocolDecoder.java:59 < ExtendedObjectDecoder.java:39 < ...)
````
After that message traccar stops listening on UDP port 5052 and not displayed in `netstat -nlu` command. I know that …
=> UDP stops listening after failure

src/org/traccar/protocol/GlobalSatProtocolDecoder.java, test/org/traccar/protocol/GlobalSatProtocolDecoderTest.java
I have a weird device [euspro sf-400](http://eus.com.ua/gps-monitoring/gps-tracker-sf400.html), which I want to connect with traccar. Unfortunately it does not have a protocol documentation, so I decided to break bad and just write to some port and read messages. Fortunately (I hope) the protocol has text format. Here are couple of message examples:
$80050377796567,0,13,281015,173437,E08513.28616,N5232.85432,222.3,0.526,,07*37!
$80050377796567,0,18,281015,191919,E08513.93290,N5232.42141,193.4,37.647,305.40,07*37!
(_I have replaced real IMEI and lon/lat numbers, but other fields were left untouched_)
The message format looks very close to the "alternative" version of `globalsat` protocol. However, there are couple of differences:
1) `fix` has something different (two digits number, `13` …
=> Another version of GlobalSat protocol

src/org/traccar/Context.java, src/org/traccar/web/WebServer.java
I want to implement a possibility to send commands from my Traccar Web UI mod. Some time ago I have already sent a pull request that allows to run both `traccar-web.war` and original traccar API for the same purpose. However, during implementation I have faced following issues:
* HTTP sessions are not shared between API and web app deployed from `traccar-web.war`. I suggest to share them.
* permissions manager object is required to validate permissions on the API side. However, it is not being initialized in 'old' web app mode. So it should be initialized if any web app is going to be started.
* the key used to look up for a user identifier in HTTP session changed from 3.2 (from `user` to `userId`). For the compatibility purpose I think that, if possible, we can stick with the `userId` …
=> Commands sending integration

src/org/traccar/geocode/GoogleReverseGeocoder.java
When is set geocoder google and `geocoder.key` , the API response is:
```json
{
"error_message" : "Requests to this API must be over SSL. Load the API with \"https://\" instead of \"http://\".",
"results" : [],
"status" : "REQUEST_DENIED"
}
```
=> Fix "Requests to this API must be over SSL" when use API Key

src/org/traccar/protocol/WondexProtocol.java, src/org/traccar/protocol/WondexProtocolEncoder.java, test/org/traccar/protocol/WondexProtocolEncoderTest.java
I've implemented few commands for Wondex protocol. It was inspired by implementation of "TotemProtocolEncoder". As I understood "KEY_DEVICE_PASSWORD" is not implemented neither in database nor in GUI, and I hardcoded it like in Totem.
=> Implemented few commands for Wondex protocol.

checkstyle.xml
It is need to lock EOL to "lf" because there is false warning about absent EOL at the end of file on windows  platform.
=> Lock EOL to "lf" to avoid warnings on windows platform

src/org/traccar/MainEventHandler.java, src/org/traccar/model/Event.java, src/org/traccar/protocol/WondexFrameDecoder.java, src/org/traccar/protocol/WondexProtocol.java, src/org/traccar/protocol/WondexProtocolDecoder.java, test/org/traccar/protocol/WondexFrameDecoderTest.java, test/org/traccar/protocol/WondexProtocolDecoderTest.java
Firstly I've made a device identification on ping packet (because it is a binary I convert it in the framedecoder to string and pass to the protocoldecoder). It helps to avoid problems then command results came before any positions received and helps to better handle device online status.
Secondly I store command result to "result" field.
And Fixed wrong class name in WondexFrameDecoderTest
It is better to identify device in framedecoder (and don't answer on ping packets) but there is not `remoteAddress` to pass `identify` function.
=> Store command result to position for wondex

src/org/traccar/web/JsonConverter.java
I noticed that `device.deofenceIds` is not sended to websocket, but by API it is accessible.
I've extended `objectToJson` to convert `List`s to JSON and `arrayToJson` to convert primitives to JSON. I've added most used primitives just to complete.
=> JsonConverter.objectToJson now can return Lists of objects or primitives

web/app/GeofenceConverter.js, web/app/store/GeofenceTypes.js, web/app/view/GeofenceMapController.js
There are coder and decoder.
They assume common `lat` `lon` order in `area`
`wktToGeometry` can be used further to draw geofences on init and to draw on edit geofence in `GeofenceMap`
=> Added geometry<->WKT coder/decoder

src/org/traccar/protocol/GranitFrameDecoder.java, src/org/traccar/protocol/GranitProtocol.java, test/org/traccar/protocol/GranitFrameDecoderTest.java, test/org/traccar/protocol/GranitProtocolDecoderTest.java
`LineBasedFrameDecoder` did not fit at all, It handles both \n and \r\n. 0x0a appears rather frequently in binary data.
`DelimiterBasedFrameDecoder` is better but we can't exclude appearing 0x0d0a in binary data, for example I can set deviceId to 2537 and never handle any position. 
Because of that I've added reading frame based on `length` field of packet. Not binary packets handled as usual with \r\n delimiter.
=> Revert GranitFrameDecoder

src/org/traccar/protocol/GranitProtocolDecoder.java
I've used the same idea with tilde and assumed that tilde has only packets with points.
If there is no tilde it is command result.
And now there is no binary to string conversion.
=> Simplify GranitProtocolDecoder command result detection

src/org/traccar/protocol/GranitProtocolDecoder.java
I was looking on jumping track and think why protocols authors choose so odd format of archive points.
Six points have same time.
I've looked in documentation and in packets, and noticed that increment equals period of reporting.
Is it me who is silly or documentation writer?
> "Одинаковые блоки по 126 байт,  каждый начинается с четырёхбайтового значения времени ( unsigned long ), затем идут шесть 20-ти байтовых записей ,  затем двухбайтовое значение инкремента ( unsigned short ), каждая из записей имеет следующую структуру:"
Is it understandable that `increment` is for time?
I would not surprise if order of points in packet is backward, because of that I took a walk with device and noticed place and time. Then I started server and get archive points.
Time and place from archive seems …
=> Increment time in archive points for Granit protocol

web/app/view/AttributesController.js, web/app/view/UserDialogController.js
Most of time, after editing only user attributes, the its record is not synced to server.
I've decided to pass whole record to editor, and set `dirty` if something changed.
=> Pass whole record to attribute editor not to lose "dirtyness"

src/org/traccar/notification/NotificationMail.java, web/app/view/AttributesController.js
According to https://javamail.java.net/nonav/docs/api/com/sun/mail/smtp/package-summary.html
> mail.smtp.from	
> Email address to use for SMTP MAIL command. This sets the envelope return address. Defaults to msg.getFrom() or InternetAddress.getLocalAddress(). NOTE: mail.smtp.user was previously used for this.
Should work and my local server on Zimbra and Gmail understand this, but mail.ru even did not accept mails until I set it via `mailMessage.setFrom`
Hope should fix this https://www.traccar.org/forums/topic/smtp-config-for-notifications/#post-6870
Other changes:
- better handle empty mail user attributes
- fix deleting attribute in attribute editor
- fix duplicating attribute if name changed
PS: sorry for duplicated commits, there was conflict and git solved it like this.
=> Fix "from" in mail notifications

src/org/traccar/api/resource/GeofencePermissionResource.java, src/org/traccar/api/resource/GeofenceResource.java, src/org/traccar/database/DataManager.java, src/org/traccar/database/GeofenceManager.java
- Split geofence refresh on 3 functions
- Enable back groupsCache
For now groupsCache have unwanted update only if device(group) linked to deleted group.
I'm researching foreign keys, but have some issues (null and not null incompatibility I think)
For demo servers you can null dead links via sql, it can help for a while.
=> Revert back groups cache and split GeofenceManager.refresh() on 3 functions

debug.xml, setup/unix/traccar.xml, setup/windows/traccar.xml, src/org/traccar/database/QueryBuilder.java, web/app/view/GroupsController.js
Solution to store `long == 0` as `NULL` in DB is not very nice, but simple. The other one is create "Zero-Group" but I do not like it, to many unpredictable side effects and changes.
I tested a bit, but did not see any regressions in other places we store `long`s.
Also there was bug in SQL request and warning in browser when editing groups
PS: also I can replace `if (value == 0)` to `if (value == 0 && name.toLowerCase().equals("groupid"))`. It will minimize side effects (if they exist)
=> Fixes for new foreign key constraints 

web/app/GeofenceConverter.js
`startsWith()` is rather new and supported only in new browsers https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith
Investigating this post https://www.traccar.org/forums/topic/problem-editing-geofence/
=> Fix geofences not showed in old browsers and IE

src/org/traccar/BaseProtocolDecoder.java, src/org/traccar/Context.java, src/org/traccar/DefaultDataHandler.java, src/org/traccar/DistanceHandler.java, src/org/traccar/FilterHandler.java, src/org/traccar/MainEventHandler.java, src/org/traccar/api/AsyncSocket.java, src/org/traccar/api/resource/DeviceResource.java, src/org/traccar/api/resource/PositionResource.java, src/org/traccar/database/ConnectionManager.java, src/org/traccar/database/DataManager.java, src/org/traccar/database/DeviceManager.java, src/org/traccar/database/GeofenceManager.java, src/org/traccar/database/IdentityManager.java, src/org/traccar/database/PermissionsManager.java, src/org/traccar/events/GeofenceEventHandler.java, src/org/traccar/events/MotionEventHandler.java, src/org/traccar/events/OverspeedEventHandler.java, test/org/traccar/ProtocolTest.java
Key changes:
1. Move unusual for `DataManager` code to `DeviceManager`
2. Move `lastPositions` from `ConnectionManager`
3. Remove `ConnectionManager` from tests and extend `IdentityManager`
That allowed:
1. Decrease locks for device manipulation (removed 2 `updateDeviceCache`)
2. Decrease locks in ConnectionManager (some `synchronised` replaced to `ConcurentHashMap`, some removed)
3. LastPosition set is in one place now (DB, cached devices objects, cached last positions) that prevent  out of sync.
4. Place for future extending device objects (attributes, sensors states and others)
Note: please note that device status via websocket is updating at the level of `DefaultDataHandler` not at `MainEventHandler`. It is before `EventHandlers`. Because sometimes toast appeared earlier than device …
=> Move code related to devices to DeviceManager

src/org/traccar/protocol/TotemProtocolEncoder.java, src/org/traccar/protocol/WondexProtocolEncoder.java
If you don't mind I used `Command.KEY_DEVICE_PASSWORD` as attribute name or may be we should use some prefix? like `"Command."+Command.KEY_DEVICE_PASSWORD`
Tested with wondex device.
=> Use password from attributes to send command

src/org/traccar/database/DeviceManager.java
Key changes:
- Incrementally update cache,  `updateDeviceCache` looks monstrous but works OK (please check it more carefully, I could miss something)
- Migrate from locks to maps, construct maps happen on first update to initialize it with right size to avoid resizing delays on every `put` (default initial capacity is 16)
- Device initialized as offline and stopped (status and motion can be easily removed from DB now)
Tested only with few devices, It would be good if you test it on one of demo servers.
=> Migrate from locks to ConcurrentHashMaps in DeviceManager

web/app/view/AttributeController.js, web/app/view/AttributeDialog.js
We can't avoid code duplicating. Requires are reverted. Attribute dialog extends `BaseDialog` directly.
This fixes cycle in requires.
Tested more carefully, there is no issues now.
Sorry again.
=> Fix attribute editing

debug.xml, schema/changelog-3.7.xml, setup/unix/traccar.xml, setup/windows/traccar.xml, src/org/traccar/api/resource/ServerResource.java, src/org/traccar/database/DeviceManager.java, src/org/traccar/database/PermissionsManager.java, src/org/traccar/events/GeofenceEventHandler.java, src/org/traccar/events/MotionEventHandler.java, src/org/traccar/events/OverspeedEventHandler.java
I've changed OverspeedEventHandler to use speed limit from attributes. Attribute name is `speedLimit`
Attribute lookup starts from Device -> Groups -> Server and Device has higher priority
Because lookup groups is expensive, I've added `event.overspeed.groupsEnabled` config to enable it.
There is two idea: rise event on every "overspeeding" point (by default) or only once during period.
`event.overspeed.riseOnce` enables it.
Also I've removed Device.status from DB. It is really small commit to separate it.
Tested for a two days. Works OK.
=> OverspeedEventHandler enhancement to use attributes

debug.xml, src/org/traccar/notification/NotificationMail.java
Sorry, I've made two of four common mistakes http://www.oracle.com/technetwork/java/javamail/faq/index.html#commonmistakes
Here is fix. Actually, It worked fine, excepting some parameters from user attributes do not applied until server restart.
Also I've added parsing `mail.smtp.ssl.trust` that allow connect to server with self-signed certificate.
=> Mail optimization

swagger.json
query parameters for GET /positions are not marked required. This allows generated clients to call /positions with or without additional parameters. Also updated Position model to include deviceId.
=> Adjusted swagger.json

src/org/traccar/api/resource/ReportResource.java, src/org/traccar/reports/Events.java, src/org/traccar/reports/Route.java, src/org/traccar/reports/Summary.java, src/org/traccar/reports/model/SummaryReport.java, web/app/Application.js, web/app/controller/Root.js, web/app/model/ReportSummary.js, web/app/store/ReportEvents.js, web/app/store/ReportRoute.js, web/app/store/ReportSummary.js, web/app/store/ReportTypes.js, web/app/view/CommandDialog.js, web/app/view/MapController.js, web/app/view/Report.js, web/app/view/ReportController.js, web/app/view/ServerDialog.js, web/app/view/UserDialog.js, web/l10n/en.json
- Changed JSON format to bare objects
- Fixed csv MIME type and added header to force browser download
- Combined some strings
- Fixed some `jscs` issues in other code
- Added `deviceId` to SummaryReport
Report still uses only one device and get all events without filtering. I wanted to get working code with not big pull request.
Route report works as before. Events and summary just fill the table.
It was not easy to find solution how download file via request with custom header `Accept`.
=> Initial implementation Report API for web interface

src/org/traccar/model/Position.java, src/org/traccar/protocol/Gl200ProtocolDecoder.java, src/org/traccar/protocol/Gps103ProtocolDecoder.java, src/org/traccar/protocol/IntellitracProtocolDecoder.java, src/org/traccar/protocol/Mta6ProtocolDecoder.java, src/org/traccar/protocol/XirgoProtocolDecoder.java
- Added `KEY_FUEL_CONSUMPTION` and `KEY_FUEL_INSTANT_CONSUMPTION`
- Fixed wrong using of `KEY_FUEL` 
About Mta6: I'm not sure what means "Fuel consumption accumulator", but pretty sure it is not `KEY_FUEL`
=> Some fuel attributes organization

src/org/traccar/protocol/WondexProtocolDecoder.java, src/org/traccar/reports/ReportUtils.java
Only wondex has optional odometer.
Anyway I've added check if both odometer values are zero they are not used to calculate distance.
There are a lot of "0.0" odometers in unit tests in different protocols. I think it is not rare case that it is zero.
=> Fixed optional odometer for wondex protocol and exclusion for 0.0 odometers

web/app/Style.js, web/app/view/MapController.js, web/app/view/Report.js
- Multiselect is deprecated for `combobox`, I used `tagfield`
- I decided to not use random for pick a color. Just used remainder on dividing `deviceId`. Color will stay the same for each device.
- Randomly generated set of colors (can be easily changed or added)
- `mapView.fit` did for first route only. Frankly, have no idea how to fit for all without edges calculating. 
Here is screenshot:
=> Colour routes of different devices

web/app/Style.js, web/app/view/Report.js
By default it grows indefinitely to right.
And it will grow down if limited only width.
=> Prevent Device tagfield growing too much

web/app/Style.js, web/app/view/GeofenceMap.js
Sorry, I did not think that `mapColorReport` used to draw geofences. (it has "report" in name)
The quickfix was just replace `mapColorReport` to `mapRouteColor[0]` but it looks not very good and I decided to separate styles used for geofences.
It will allow some fine tuning and avoid such confuses in future.
=> Fix geofences colors and separate geofences styles

src/org/traccar/protocol/OsmAndProtocolDecoder.java, test/org/traccar/protocol/OsmAndProtocolDecoderTest.java
As exposed on forum thread - https://www.traccar.org/forums/topic/tracking-through-http-url-request/ - add location parameter to OsmAnd protocol for coma separated lat & lon (“&location=60.0,30.0”).
=> Adding location parameter to OsmAnd protocol

src/org/traccar/web/CsvBuilder.java
- Make `attributes` always last column
- Format Map object as simple string instead of json
Here is an example
[report (4).zip](https://github.com/tananaev/traccar/files/471907/report.4.zip)
=> Small csv export improvement

debug.xml, src/org/traccar/protocol/JpKorjarFrameDecoder.java, src/org/traccar/protocol/JpKorjarProtocol.java, src/org/traccar/protocol/JpKorjarProtocolDecoder.java, test/org/traccar/protocol/JpKorjarProtocolDecoderTest.java
Hi,
I have recently been tidying up shelves in my room and I found 2 GPS devices that I bought in 2008 or so. 
They are using their own text protocol. I added support for this protocol to traccar.
So far it works fine for me, so someone might find it useful if it becomes built-in.
There isn't really any documentation for this protocol but it's pretty self explainatory. 
The only problem I see is that at least one of my devices never reports the correct course (always returns the same number) but afaik it has been like that from the beginning (presumably some bug in the device's firmware)
The code could have been more compact if it used the regexp patterns, but I am not that well versed to do it right.
=> Add jpkorjar protocol support

tools/hex.sh
This change allows us to use this nice script with hosts other than localhost.
Shell variables unprotected by double-quotes can cause shell-commands to be executed by the script.  It's a security vulnerability.  The quotes make sure only quote-expansion is allowed.  For instance, variables will be substituted for their values, but no shell commands will be expanded.  I effectively consider quote-unprotected variables as syntax errors --- I never write them this way.
=> Adds support for specifying a host.

debug.xml, schema/changelog-3.8.xml, src/org/traccar/Context.java, src/org/traccar/api/resource/AttributeAliasResource.java, src/org/traccar/api/resource/DeviceResource.java, src/org/traccar/database/AliasesManager.java, src/org/traccar/database/DataManager.java, src/org/traccar/model/AttributeAlias.java, src/org/traccar/web/WebServer.java
Added attributes aliases (server part)
- It is just cache, proxy functions and API resources
- Used `id` to simplify update and remove
- Added unique constraint to deviceId-attribute to exclude duplicate attributes per device
Sometimes I used `alias` instead of `attributeAlias` just not to do long names.
=> Add attributes aliases

debug.xml, src/org/traccar/BaseProtocolDecoder.java
The feature is automatic adding of unknown devices.  To make this happen, I had to fix the name of the default group.  I chose "The default group".  If I choose an ID, such as ID=1, then this change would not merge well with existing installations.
Here's a SUNTECH meeting the server for the first time.  Server is glad to meet the new device and annotates that in the log.  Other than that, everything flows as if the device was already known.
```
2016-09-20 11:43:02  INFO: [33C73632] connected
2016-09-20 11:43:02 DEBUG: [33C73632: 5011 < 192.168.0.49] HEX: 5354333030414c543b3230353535363535313b30353b3436393b32303136303931333b31383a34393a35373b3136626431343b2d32322e3839363536313b2d3034332e3132323036343b3031302e3532313b3038342e36303b303b303b373236363b32342e33393b3030303030303b393b303030313439 …
```
=> Adds unknown devices automatically.

src/org/traccar/protocol/Jt600Protocol.java, src/org/traccar/protocol/Jt600ProtocolEncoder.java, test/org/traccar/protocol/Jt600ProtocolEncoderTest.java
I have added following commands implementations:
* Engine start
* Ending stop
* Set Timezone
* Reboot device
Also tests were added. All commands are sent via text, so I am not sure that it is acceptable for the binary version of protocol.
=> For JT600c - added engine start/stop, set timezone and reboot commands implementations

src/org/traccar/protocol/Gl200Protocol.java, src/org/traccar/protocol/Gl200ProtocolDecoder.java, src/org/traccar/protocol/Gl200ProtocolEncoder.java
- Remove hardcoded password from commands, there is no default one, it depends on device model.
- Authenticate a device on heartbeat stage and reply only to registered devices. It will make the device online and allow send commands before a position received
=> GL200: Password for commands and heartbeat authentication

src/org/traccar/protocol/NavisProtocolDecoder.java
The numbering of the months in Navis protocol starts with 0
=> Fix month decode in Navis protocol

setup/docker/Dockerfile
Non-root user causes build error on Docker.
When user is non-root, Docker build stops:
```
Sending build context to Docker daemon 19.27 MB
Step 1 : FROM java:8-alpine
---> 7c2c8f354ab3
Step 2 : MAINTAINER Danilo Recchia <danilo.recchia@vortus.solutions>
---> Running in d7ca8033cd63
---> fb9b743ad434
Removing intermediate container d7ca8033cd63
Step 3 : RUN apk upgrade --update &&     apk add --update curl bash &&     rm -rf /var/cache/apk/* &&     mkdir -p /opt/traccar/logs &&     mkdir -p /opt/traccar/data
---> Running in ba377d2489aa
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/6) Upgrading libcrypto1.0 (1.0.2i-r0 -> 1.0.2j-r0)
(2/6) Upgrading libssl1.0 (1.0.2i-r0 -> …
```
=> Fix current user for alpine in Dockerfile

debug.xml, src/org/traccar/BasePipelineFactory.java, src/org/traccar/CopyAttributesHandler.java
Base simple version without expiration
User can enable it by setting `<entry key='processing.copyAttributes.enable'>true</entry>`
and set list of attributes separated by space in `processing.copyAttributes` (device->group->config)
fix #2325
=> Copy some attributes from last position

src/org/traccar/api/resource/DeviceResource.java, src/org/traccar/database/DeviceManager.java, src/org/traccar/model/DeviceTotalDistance.java
I have some doubts about API path, leaved `{id}` for consistency.
Only admins are allowed to reset `totalDistance`.
Just re-add  last position with corrected attribute. If there is no last position do nothing (and throw exception to notify user)
Will be thankful for advice where to place it to web-interface. I'm thinking of placing `textfield` and `button` in device edit dialog. Or make new dialog and call it from settings menu?
=> Implement reset total distance API

src/org/traccar/CoordinatesHandler.java
I've extended a bit `CoordinatesHandler`.
Some devices send wrong coordinates  when can not fix GPS ( 0.0/0.0 or with wrong sign like Granit) but send useful information about sensors or alarms that shouldn't be filtered.
Like "too small shift" I added "too big shift" that is replaced with last coordinates.
=> Add maximum coordinates error to CoordinatesHandler

src/org/traccar/CoordinatesHandler.java
It should prevent problem you mention in #2480 
Valid position with "too big shift" should not be replaced with last coordinates.
=> Add exclusion for valid positions to CoordinatesHandler

src/org/traccar/api/resource/PositionResource.java, src/org/traccar/api/resource/ReportResource.java, src/org/traccar/api/resource/StatisticsResource.java, src/org/traccar/helper/DateUtil.java, src/org/traccar/reports/Events.java, src/org/traccar/reports/Route.java, src/org/traccar/reports/Summary.java, src/org/traccar/reports/Trips.java
There are two commits:
- Removed explicit conversion to JSON from reports
- Move `parseDate` to `DateUtil`
`JsonConverter` leaved as is.
=> Remove explicit JSON conversion from reports

src/org/traccar/protocol/GranitProtocolDecoder.java
From devices documentation:
> Ain0  - аналоговый вход прибора (оранжевый провод), по умолчанию запрограммированный на измерение внутреннего напряжения прибора. При измерении внутреннего напряжения прибора значения входного напряжения колеблются в диапазоне от 0 до 40В. При перепрограммировании, на измерения аналогового входа, значения воспринимаются в диапазоне от 0 до 5В.
Ain1 - аналоговый вход прибора (бело-оранжевый провод), принимающий измерения в диапазоне от 0 до 5 В.
Ain2 - аналоговый вход прибора (коричневый провод), принимающий измерения в диапазоне от 0 до 30 В.
Ain3 - аналоговый вход прибора (бело-коричневый провод), принимающий измерения в диапазоне от 0 до 30 В.
Here is small improvement to allow users convert this values to volts.
If the configuration is default `adc1Ratio` …
=> Granit: Analog input values tuning

schema/changelog-3.8.xml, setup/default.xml, src/org/traccar/api/resource/SessionResource.java, src/org/traccar/api/resource/UserResource.java, src/org/traccar/database/PermissionsManager.java, src/org/traccar/model/User.java
Here is nice addition to users disabling.
Main reason is to give link user to traccar site without username/password
User can have a token, that can be used to authorization via GET parameter instead of username/password:
`https://demo.traccar.org/api/session?token=s5XpfXKZ3zLi7X4A`
Only Admin can add/change token to user.
Also hardcoded minimal token length and symbols to use in token.
Security note: tokens should be used very carefully and mostly with read only users in combination with expiring. Only over HTTPS. Because `GET` parameters is absolutely unsecured and cached/logged everywhere.
=> Implement users tokens

pom.xml
[INFO] Copying mssql-jdbc-6.1.0.jre8.jar to /root/traccar/target/lib/mssql-jdbc-6.1.0.jre8.jar
sample config for mssql
```
<entry key='database.driverFile'>lib/mssql-jdbc-6.1.0.jre8.jar</entry>
<entry key='database.driver'>com.microsoft.sqlserver.jdbc.SQLServerDriver</entry>
<entry key='database.url'>jdbc:sqlserver://[serverName][\instanceName];user=[userName];password=[password];databaseName=[database];</entry>
<entry key='database.user'>[userName]</entry>
<entry key='database.password'>[password]</entry>
```
=> Add lib for Microsoft JDBC Drivers with maven

setup/default.xml, src/org/traccar/BasePipelineFactory.java, src/org/traccar/events/MaintenanceEventHandler.java, src/org/traccar/model/Event.java, src/org/traccar/notification/NotificationFormatter.java
Here is implementation of "maintenance is needed" events.
Two configuration attributes:
- `device.maintenanceStart` zero if ommited 
- `device.maintenanceInterval` can't be zero
Both in meters
Example:
`device.maintenanceStart = 2000000`
`device.maintenanceInterval = 7500000`
Events will be generated once at the point then `totalDistance` overcome 2000 km, 9500 km, 17000 km, 24500 km and so on.
Also:
- Enabled `statusHandler` by default (or it was disabled intentionally? )
- Added mail templates for new event types
=> Maintenance events

src/org/traccar/api/resource/UserResource.java
- for `deviceLimit` and `expirationTime`.
Can we do something like this? Regarding #2589 
Two new config properties
- `default.deviceLimit `
- `default.expirationDuration` in days. To be counted from user creation date.
This would not affect user creation by admin.
PS: I know very little java.
=> Add option to set some default User properties

src/org/traccar/geofence/GeofenceGeometry.java, src/org/traccar/geofence/GeofencePolygon.java, src/org/traccar/geofence/GeofencePolyline.java, src/org/traccar/helper/DistanceCalculator.java, src/org/traccar/model/Geofence.java, test/org/traccar/geofence/GeofenceCircleTest.java, test/org/traccar/geofence/GeofencePolygonTest.java, test/org/traccar/geofence/GeofencePolylineTest.java, test/org/traccar/helper/DistanceCalculatorTest.java
fix  #2600 
Polyline Geofence consider to contains point if distance between point and at least one interval less than predefined
Default value for `geofence.polylineDistance` is 25 meters. It is with wide margins.
Also moved `Coordinate` class to parent for use it in both polyline and polygon.
=> Implemented polyline geofence

src/org/traccar/api/resource/PositionResource.java
It will short request
`http://localhost:8082/api/positions?id=15661&id=15661&id=15661&id=15662&id=15662&id=15663&id=15663&id=15663&id=15664&id=15664&id=15665&id=15667&id=15673&id=15677&id=15680&id=15680&page=1&start=0&limit=25`
=> Use "id" parameter instead of "positionId"

swagger.json
I don't think
```
header: {}
```
is not required from any of the responses. I haven't removed it from all of the endpoints though.
I included Markdown formatting in few of the texts. It seems prettier when I view it on some API browsers. :)
=> Update API specs with /positions

schema/changelog-3.9.xml, schema/changelog-master.xml, setup/default.xml, src/org/traccar/api/resource/NotificationResource.java, src/org/traccar/database/NotificationManager.java, src/org/traccar/model/Notification.java
- Extended model
- Copy values with help of DB changelog
- Remove notification only if everything is false and attributes is empty.
- Merge all types of notifications with actual user notifications on server side. 
Also tested on MSSQL, works fine.
=> Use model instead of attributes to store Notification options

src/org/traccar/notification/NotificationMail.java
fix #2651 
I don't think we should investigate why it does not work by default, may this parameter will help somebody else.
=> Add support for "mail.smtp.ssl.protocols" parameter

pom.xml, src/org/traccar/Context.java, src/org/traccar/notification/MailMessage.java, src/org/traccar/notification/NotificationFormatter.java, src/org/traccar/notification/NotificationMail.java, templates/mail/alarm.vm, templates/mail/commandResult.vm, templates/mail/deviceMoving.vm, templates/mail/deviceOffline.vm, templates/mail/deviceOnline.vm, templates/mail/deviceOverspeed.vm, templates/mail/deviceStopped.vm, templates/mail/deviceUnknown.vm, templates/mail/geofenceEnter.vm, templates/mail/geofenceExit.vm, templates/mail/ignitionOff.vm, templates/mail/ignitionOn.vm, templates/mail/maintenance.vm, templates/mail/unknown.vm
I used Velocity Engine.
Initiated engine in `Context` because we have to disable default velocity logger. Also set templates path.
It could be done in `formatMessage` function, but better do it once. I think `Context` is right place.
I think it is not good idea to have separate templates for body and subject. I made small trick.
Set variable `$Subject` in template (first line in every .vm file) and then retrieve it after merging.
[VTL](https://velocity.apache.org/engine/1.7/vtl-reference.html) is not so powerful as [JEXL](http://commons.apache.org/proper/commons-jexl/reference/syntax.html) but I think it will be able do all necessary things.
Templates leaved as was except links.
=> Templates for mail notifications

pom.xml, schema/changelog-3.10.xml, schema/changelog-master.xml, setup/default.xml, src/org/traccar/Context.java, src/org/traccar/api/resource/CalendarPermissionResource.java, src/org/traccar/api/resource/CalendarResource.java, src/org/traccar/database/CalendarManager.java, src/org/traccar/database/DataManager.java, src/org/traccar/database/PermissionsManager.java, src/org/traccar/database/QueryBuilder.java, src/org/traccar/events/GeofenceEventHandler.java, src/org/traccar/model/Calendar.java, src/org/traccar/model/CalendarPermission.java, src/org/traccar/model/Geofence.java, test/org/traccar/calendar/CalendarTest.java
Implemented `Calendar` class that uses [iCal4j](https://github.com/ical4j/ical4j) to parse `ics` files.
Key changes:
- Simple permissions management (link calendar to user)
- Added `calendarId` to `Geofence` class
- `checkMoment` function makes simple trick. It filters calendar for period one second duration and check if there is any `VEVENT` after filtering.
Geofences are always calculated, but if geogence has linked calendar and `fixTime` is not in any VEVENT, Enter/Exit `Event` is not generated.
Also added support to read/save `byte[]` as `BLOB` to `QueryBuilder`
=> Calendars implementation

schema/changelog-3.10.xml, setup/default.xml, src/org/traccar/api/resource/DevicePermissionResource.java, src/org/traccar/api/resource/DeviceResource.java, src/org/traccar/api/resource/UserResource.java, src/org/traccar/database/PermissionsManager.java, src/org/traccar/model/User.java
Here is changes discussed #2810 
- Add "deviceReadonly" user field. Such user can not add/edit/delete devices.
- Allow users edit `token`s
- `deviceLimit = 0` means zero, not infinite 
- Managers can create users with `deviceLimit = 0` only
- `userLimit = 0` means ordinary user
- `userLimit = -1` means manager without user limit
- Manager can't create users with `expirationTime` later then their
- Only admin can unlink devices from himself
- Readonly user becomes totally readonly
- Other discussed permissions improvements
=> Permissions improvements

src/org/traccar/model/WifiAccessPoint.java
Some geolocation providers also accept wifi channel number
to perfom the geolocation more precisely. So protocols can
supply this additional information now.
=> Added channel to WifiAccessPoint geolocation class

src/org/traccar/GeolocationHandler.java
When geolocation found a lat/lon from LBS/WIFI, only lat/lon and
accuracy are updated.
If protocol has copied "last" position to "Position" class before
issuing the geolocation, then all other parameters of GPS position
will be invalid (from "last" position).
So this fix reset to 0 the altitude, speed, course and rssi.
=> Reset additional parameters of GPS position after geolocation

src/org/traccar/geolocation/UniversalGeolocationProvider.java
Google geolocation API does not work correctly if
"Content-Type:application/json" is not present in http header.
=> Set Content Type in http header of geolocation request

src/org/traccar/notification/EventForwarder.java
Removed user agent (default will be `User-Agent: AHC/1.0`)
Set content type to `application/json`
`event.forward.header` will override default values.
=> Event forward header small improvement

src/org/traccar/api/resource/CommandResource.java
It is can be controversial, but I think readonly and device readonly users should not be able send commands.
=> Do not allow readonly users send commands

src/org/traccar/protocol/MxtProtocolDecoder.java
The last fix generated out of memory error because it was writing into the same buffer it was reading from.
I tested it online with a device and it's now working. The byte stuffing is ok too.
=> Fix MXT protocol response

src/org/traccar/events/IgnitionEventHandler.java
In some cases we need to get ignition event even if position is not valid. For example if car starts in underground parking.
fix #2911
=> Remove check for valid in IgnitionEventHandler

checkstyle.xml, src/org/traccar/protocol/AplicomProtocolDecoder.java, src/org/traccar/protocol/AtrackProtocolDecoder.java, src/org/traccar/protocol/AutoFonProtocolDecoder.java, src/org/traccar/protocol/BceProtocolDecoder.java, src/org/traccar/protocol/CellocatorProtocolDecoder.java, src/org/traccar/protocol/CguardProtocolDecoder.java, src/org/traccar/protocol/FlextrackProtocolDecoder.java, src/org/traccar/protocol/GpsmtaProtocolDecoder.java, src/org/traccar/protocol/Jt600ProtocolDecoder.java, src/org/traccar/protocol/MeitrackProtocolDecoder.java, src/org/traccar/protocol/MxtProtocolDecoder.java, src/org/traccar/protocol/TeltonikaProtocolDecoder.java, src/org/traccar/protocol/TotemProtocolDecoder.java, src/org/traccar/protocol/TramigoProtocolDecoder.java, src/org/traccar/protocol/TrvProtocolDecoder.java, src/org/traccar/protocol/Tt8850ProtocolDecoder.java
I have updated a number of protocols to record CellTower information.  Where CellTower information is reported, I have deleted KEY_RSSI as it is provided with the CellTower and would be redundant.
I have updated a number of protocols to record a number of KEYS as described and matched in the protocol comments.
=> CellTowers and capturing additional protocol information

src/org/traccar/reports/Events.java, src/org/traccar/reports/Route.java, src/org/traccar/reports/Trips.java
There is some limitations in worksheet names, we need use safe naming.
http://stackoverflow.com/questions/451452/valid-characters-for-excel-sheet-names
http://poi.apache.org/apidocs/org/apache/poi/ss/util/WorkbookUtil.html#createSafeSheetName(java.lang.String)
> Invalid characters are replaced by one space character ' '
For example device name `Test[2]` will look `Test 2 `
fix #2955
=> Safely name sheets for excel reports

src/org/traccar/api/resource/SessionResource.java
We need it to correctly pass emails and passwords with symbols and international
Both parameters must be "escaped" "base64" "UTF8" string
`admin` -> `YWRtaW4=` -> `YWRtaW4%3D`
`pa$$word` -> `cGEkJHdvcmQ=` -> `cGEkJHdvcmQ%3D`
`пароль` -> `0L/QsNGA0L7Qu9GM` -> `0L/QsNGA0L7Qu9GM`
=> Wait cookie credentials in base64

src/org/traccar/smpp/SmppClient.java
There is a case:
Some users may want send notifications from short or alphanumeric number, but commands should be send from "routable" international or national number to catch answer from device.
Also there may be different price for SMSs from short number and from "routable" number. Commands are not so frequent as notifications and it may allow save some money.
Added 3 new optional config parameters in this way: if `commandSourceAddress` omitted used `sourceAddress`. Same for TON and NPI.
=> SMPP: Allow set different source address for commands

src/org/traccar/database/DeviceManager.java, src/org/traccar/events/TextMessageEventHandler.java, src/org/traccar/model/Event.java, src/org/traccar/smpp/ClientSmppSessionHandler.java, templates/mail/textMessage.vm, templates/sms/textMessage.vm
Key changes:
- Schema changes applies to "non-mssql" DB engines only. It "nulls" all "phone" duplicates and add unique constraint
- Added map phone -> devices
- Added new type of Event - `textMessage`
If DB is MS then behavior will be next: In case phone has duplicates last added device will be mapped.
Frankly, I do not like the changes very much, especially null phone if it is `""` in `addDevice` and  `updateDevice` methods. Only multiple nulls are possible with unique constraint and it comes as `""` from web-client by default.
But I do not have other more beautiful solution may be you have another idea...
=> Handle incoming SMS from devices as Event

src/org/traccar/database/DeviceManager.java, src/org/traccar/model/Device.java
I'm working on filtering in web-part discussed in #3025 
By default new device will have `""` as status and handle fourth value (empty string) is very very inconvenient and break logic.
=> Set status to offline for new device

src/org/traccar/notification/NotificationFormatter.java, src/org/traccar/reports/ReportUtils.java, templates/mail/deviceOverspeed.vm, templates/sms/deviceOverspeed.vm
Pass `NumberTool` object to templates (also to reports for consistence and case if somebody wants use decimal format)
Also adjusted notification templates to format one digit after point. Used intermediate variable `$speedValue`, because we can not use math everywhere, just in `#set`.
Did not change report templates, because it is already formatted with help of `String.format()`
fix #3049
=> Format speed in notification templates

src/org/traccar/protocol/EnforaProtocol.java, src/org/traccar/protocol/EnforaProtocolEncoder.java
Hi
wanted to share with you this implementation of the EnforeEncoder, tested and working on 2818.
It was implemented following documentation on http://documentation.nvtl.com/board/download/file.php?id=221, on TCP protocol
Hope you find it useful for others.
=> Added EnforaEncoder tested on 2818

src/org/traccar/model/Position.java, src/org/traccar/protocol/MeitrackProtocolDecoder.java
Adding new Events:
- External power restored (reported by device, event code 22) - ALARM_POWER_RESTORED
- External power cut (reported by device, event code 23) - ALARM_POWER_CUT
Modifing Events:
- Event code 18 reports ALARM_LOW_POWER (instead of ALARM_POWER_CUT)
=> Adding and correcting event codes for Meitrack

setup/docker/build.sh, src/org/traccar/Config.java, test/org/traccar/config/EnvVarTest.java
When working with Docker, passing environment variables is more practical than using a configuration file.
This PR changed the `Config` class to look for an environment variable before checking the pre-configured configuration files.
There is an UPPERCASE_SNAKE rule applied to properties names.
Ex:
forward.url --> FORWARD_URL
database.driver --> DATABASE_DRIVER
=> Environment variables

src/org/traccar/protocol/Gt06ProtocolDecoder.java
Hi Anton 
Currently GT06 command response is not creating CommandResult event as it is been treated as command and not result. 
This change will help to handle custom command results as events.
Thanks
=> Change GT06 command result to result key from command key.

src/org/traccar/protocol/XexunProtocolDecoder.java
Updated xexun protocol to be able to use kmh as source speed.
see https://www.traccar.org/forums/topic/wrong-speed-at-reports/
=> Extend xexun protocol - kn and kmh

schema/changelog-3.12.xml, setup/default.xml, src/org/traccar/BasePipelineFactory.java, src/org/traccar/Context.java, src/org/traccar/api/resource/AttributePermissionResource.java, src/org/traccar/api/resource/AttributeResource.java, src/org/traccar/api/resource/DeviceAttributeResource.java, src/org/traccar/api/resource/GroupAttributeResource.java, src/org/traccar/database/AttributesManager.java, src/org/traccar/database/DataManager.java, src/org/traccar/database/PermissionsManager.java, src/org/traccar/model/Attribute.java, src/org/traccar/model/AttributePermission.java, src/org/traccar/model/DeviceAttribute.java, src/org/traccar/model/GroupAttribute.java, src/org/traccar/processing/ComputedAttributesHandler.java, src/org/traccar/processing/CopyAttributesHandler.java, test/org/traccar/processing/ComputedAttributesTest.java
Here is implementation.
Structure are very similar to Attribute Aliases. ComputedAttributes are linked to device. Manager and api.resource almost copy.
`ComputedAttribute` model has following fields:
`id`
`deviceId`
`expression` - JEXL expression to compute
`attribute` - name of attribute, where result will be placed
`type` - is type to which result will be cast (number/boolean/string)
Manager is always working, but processing itself can be disabled (in case of performance issues)
I placed `ComputedAttributesHandler` after `CopyAttributes` and before Events handlers.
Also I've moved `CopyAttributesHandler` to `processing` package.
=> Implement computed attributes

src/org/traccar/processing/ComputedAttributesHandler.java, test/org/traccar/processing/ComputedAttributesTest.java
Map all position fields and attributes to jexl context with help of reflection.
Expressions look more simple now.
Did not notice any changes in performance.
Added some tests to check if scripts can influence on the original position.
=> Unwrap position fields and attributes to computedAttribute context

src/org/traccar/model/Position.java, src/org/traccar/protocol/Ardi01ProtocolDecoder.java, src/org/traccar/protocol/CguardProtocolDecoder.java, src/org/traccar/protocol/DishaProtocolDecoder.java, src/org/traccar/protocol/Gl200ProtocolDecoder.java, src/org/traccar/protocol/GlobalSatProtocolDecoder.java, src/org/traccar/protocol/GoSafeProtocolDecoder.java, src/org/traccar/protocol/GpsMarkerProtocolDecoder.java, src/org/traccar/protocol/H02ProtocolDecoder.java, src/org/traccar/protocol/Jt600ProtocolDecoder.java, src/org/traccar/protocol/OsmAndProtocolDecoder.java, src/org/traccar/protocol/T55ProtocolDecoder.java, src/org/traccar/protocol/TaipProtocolDecoder.java, src/org/traccar/protocol/TotemProtocolDecoder.java, src/org/traccar/protocol/WatchProtocolDecoder.java, src/org/traccar/protocol/WondexProtocolDecoder.java, src/org/traccar/protocol/XirgoProtocolDecoder.java, src/org/traccar/protocol/Xt013ProtocolDecoder.java, test/org/traccar/ProtocolTest.java
Here is part of big common position attributes improvement.
`KEY_BATTERY` and `KEY_BATTERY_LEVEL` today
Added test for number and percents.
One half changed according to documentation, second half according to intuition and logic.
I supposed that `(d+.d+)` usually voltage and `(dd)` usually percents.
The only protocol I do not know how interpret is `taip`, there are only three values in tests: `229`, `4416` and `4190` and no documentation. I have no idea how handle it. Just converted to integer to not fail tests.
=> Adjust battery and batteryLevel type

src/org/traccar/protocol/AquilaProtocolDecoder.java, src/org/traccar/protocol/BlackKiteProtocolDecoder.java, src/org/traccar/protocol/GoSafeProtocolDecoder.java, src/org/traccar/protocol/IntellitracProtocolDecoder.java, src/org/traccar/protocol/TrakMateProtocolDecoder.java, src/org/traccar/protocol/VisiontekProtocolDecoder.java, test/org/traccar/ProtocolTest.java
Organized `KEY_POWER` and `KEY_CHARGE` using in few places
- Sorry, reverted `KEY_POWER` without default value in GoSafe (from last PR)
- "chargerPressure" has nothing to `KEY_CHARGE` in Intellitrac, it is about turbine or compressor or something
- I'm not sure in BlackKite, there is no documentation and any description, but it looks like `KEY_CHARGE`
- And I'm pretty sure that it is `KEY_CHARGE` in Visiontek
=> Organize KEY_POWER and KEY_CHARGE

src/org/traccar/protocol/CityeasyProtocolDecoder.java, src/org/traccar/protocol/CradlepointProtocolDecoder.java, src/org/traccar/protocol/DishaProtocolDecoder.java, src/org/traccar/protocol/GoSafeProtocolDecoder.java, src/org/traccar/protocol/HaicomProtocolDecoder.java, src/org/traccar/protocol/MegastekProtocolDecoder.java, src/org/traccar/protocol/MeitrackProtocolDecoder.java, src/org/traccar/protocol/T55ProtocolDecoder.java, src/org/traccar/protocol/TaipProtocolDecoder.java, src/org/traccar/protocol/TotemProtocolDecoder.java, src/org/traccar/protocol/Tr900ProtocolDecoder.java, src/org/traccar/protocol/TrackboxProtocolDecoder.java, src/org/traccar/protocol/V680ProtocolDecoder.java, src/org/traccar/protocol/VisiontekProtocolDecoder.java, src/org/traccar/protocol/XexunProtocolDecoder.java, src/org/traccar/protocol/XirgoProtocolDecoder.java, src/org/traccar/protocol/Xt013ProtocolDecoder.java, test/org/traccar/ProtocolTest.java
Next portion...
Satellites was most easier.
Supposed that RSSI is float dBm value or 0..31 signal strength.
V680 is not RSSI at all, it can contain lbs data
As for Megastek... checked again documentation and fixed battery and power. Also according to documentation satellites can be only number, but some test cases has "0/3" or "0/8" values, I believe that it is used and visible number of satellites.
I checked `KEY_GPS` using for next changes and become upset. It used for very different data.
Frankly, it is very thankless work, organize attributes without documentation. I'm going to make a pause.
=> Organize satellites and RSSI values

schema/changelog-3.12.xml
Adjusted some foreign key names to `fk_[baseTableName]_[baseColumnNames]` scheme
fix #3197 
Changing `positions` table may take a while.
=> Organize foreign key names

src/org/traccar/model/Command.java, src/org/traccar/protocol/WondexProtocol.java, src/org/traccar/protocol/WondexProtocolDecoder.java, src/org/traccar/protocol/WondexProtocolEncoder.java
Didn't show $MSG messages from the tracker, example hex:
2017-06-02 21:43:43 DEBUG: [BEEC07FB: 5032 < 2.247.253.121] HEX: 244d53473a47534d494e464f3d6e65747a636c75622b2c33302c312c300d0a
-> $MSG:GSMINFO=netzclub+,30,1,0[13][10]
Identifaction was wrong, result from the Tracker was the Version; Version added and Identification corrected, added Battery Status and GSM Status, as also added in the command.java and wondexprotocol.java and in the webfile
Added gsmstatus and devicestatus commands for wondexprotocol
=> Wondex upgrade and fix for a little missing thing

src/org/traccar/database/DeviceManager.java
Enumerate managed devices as `Set` to exclude duplicates
fix #3238
=> Fix managed devices enumerating

setup/default.xml, src/org/traccar/protocol/OwnTracksProtocol.java, src/org/traccar/protocol/OwnTracksProtocolDecoder.java, test/org/traccar/protocol/OwnTracksProtocolDecoderTest.java
This pull request implements a new protocol called `owntracks` which decodes JSON publishes by the [OwnTracks](http://owntracks.org) apps running on iOS or Android. These open source apps originally did MQTT (and still do of course), but a while ago we added HTTP POST which posts JSON payloads such as
```json
{"cog":271,"lon":2.29513,"acc":5,"vel":61,"vac":21,"lat":48.85833,"tst":1497350249,"alt":167,"_type":"location","tid":"JJ"}
```
Traccar's deviceId is gleaned from OwnTracks' `tid` (tracker ID) which is a 2-character code. The other elements ought to be self-explanatory and are all mapped onto appropriate Traccar parameters.
We (i.e. the OwnTracks team) hope this is a valuable contribution to the excellent Traccar project and would like to see this in Traccar to enhance …
=> New protocol decoder for OwnTracks

src/org/traccar/protocol/OwnTracksProtocolDecoder.java, test/org/traccar/protocol/OwnTracksProtocolDecoderTest.java
You kindly merged, the new [OwnTracks Protocol Decoder](https://github.com/tananaev/traccar/pull/3242), and this pull request attempts to address some things I omitted the first time around. In particular:
1. Ensures most attributes in [OwnTracks JSON](http://owntracks.org/booklet/tech/json/#_typelocation) are optional: only `lat`, `lon`, and `_type` are mandatory.
2. Checks for payloads of `"_type" : "location"` and uses only those. (OwnTracks has other payload types, e.g. "transition" which probably shouldn't be used in Traccar.)
3. Addresses an originally too simplistic method of creating a Traccar _deviceId_ using our _tracking ID_ (`tid`). Starting now, if the payload contains our `topic` (e.g. `owntracks/jpmens/iphone5s`) that will be used in preference to avoid collisions.
4. Adds …
=> Solidify OwnTracks protocol decoder

src/org/traccar/reports/ReportUtils.java, src/org/traccar/reports/model/TripsConfig.java, test/org/traccar/reports/ReportUtilsTest.java
Introduced `report.trip.minimalNoDataDuration` config parameter. It is 0 (disabled) by default.
Check time between current and "next" position if gap is more than config, then this is start of parking period.
=> Detect Trips and Stops by gaps in data

src/org/traccar/FilterHandler.java, src/org/traccar/protocol/WondexProtocolDecoder.java, test/org/traccar/protocol/WondexProtocolDecoderTest.java
"filter.invalid" filters now impossible positions. 
In Wondex protocol answers to messages are no longer marked as invalid, even without position.
Sat over 2 check removed.
Wondex decoder test changed to pass because of the removed Sat over 2 check
=> Filter Invalid upgrade and Wondex fix

src/org/traccar/protocol/OwnTracksProtocolDecoder.java
OwnTracks apps can publish payloads with distinct `_type`s in the JSON payload, but Traccar should process only `_type: location`. However, if the apps publish, say, a `_type: transition` and Traccar returns 400, the app will continue to attempt delivery for ever.
This PR fixes that by having Traccar return HTTP status 200 to the apps, indicating "ok" but otherwise i gnoring that particular data.
=> Correctly ignore OwnTracks publishes of type != location

src/org/traccar/BasePipelineFactory.java
Moved `geocoder` down in pipeline after `filter` to prevent unnecessary requests.
=> Do reverse geocoding after filtering

src/org/traccar/reports/ReportUtils.java, src/org/traccar/reports/model/BaseReport.java, test/org/traccar/reports/ReportUtilsTest.java
If I'm not mistaken when reports was implemented we do not have standardized `KEY_FUEL_LEVEL` type and used string for reports. I thing it is time to make it correct.
Moreover there is warnings in logs when export reports for device without `KEY_FUEL_LEVEL` attribute.
````
INFO|27168/0|Service traccar|17-06-20 16:42:18|[qtp30275617-44] WARN org.apache.commons.jexl2.JexlEngine - org.jxls.expression.JexlExpressionEvaluator.evaluate@61![0,14]: 'trip.spentFuel;' inaccessible or unknown property trip
INFO|27168/0|Service traccar|17-06-20 16:42:18|[qtp30275617-44] WARN org.apache.commons.jexl2.JexlEngine - org.jxls.expression.JexlExpressionEvaluator.evaluate@61![0,14]: 'trip.spentFuel;' inaccessible or unknown property trip
INFO|27168/0|Service traccar|17-06-20 16:42:18|[qtp30275617-44] WARN …
```
=> Change type of 'spentFuel' to double

src/org/traccar/protocol/OsmAndProtocolDecoder.java
=> Osmand: Store 'batt' parameter as 'batteryLevel'

src/org/traccar/protocol/OwnTracksProtocolDecoder.java
This pull request corrects an embarassing error.
=> OwnTracks velocity is in km/h not cps

src/org/traccar/processing/ComputedAttributesHandler.java
Mapped attributes only and as is. If position has attributes with same names, they will replace device attributes.
fix #3347 
fix #3333
=> Map Device attributes to Computed Attributes

src/org/traccar/api/resource/DeviceResource.java, swagger.json
This pull request adds the possibility to GET a device with its `uniqueId`. Modelled after `Id`, we also accept a list of `uniqueId`. Basically, if `all` is false, we collect devices by `Id` and `uniqueId` and return those.
Hence, the following GET request is possible:
```
http://127.0.0.1:8082/api/devices?uniqueId=9876543210987654&id=11
```
=> [NEW] add GET with list of uniqueId to API

src/org/traccar/database/AttributesManager.java, src/org/traccar/database/CalendarManager.java, src/org/traccar/database/DataManager.java, src/org/traccar/database/DeviceManager.java, src/org/traccar/database/DriversManager.java, src/org/traccar/database/ExtendedObjectManager.java, src/org/traccar/database/GeofenceManager.java, src/org/traccar/database/PermissionsManager.java, src/org/traccar/database/QueryBuilder.java, src/org/traccar/database/SimpleObjectManager.java
Polished few things:
- Items cache:
- Reorganized cache update, now it is similar to how we do it for Devices and Groups (do not clear items map, but update every item)
- Used "overridable" functions `addNewItem`/`updateCachedItem` for two purposed update cache and update items. By default it just `put` but might be used to track additional maps (like uniqueIds) or update item by fields.
- It is not necessary to override whole functions `addItem`/`updateItem`/`removeItem` and especially `refreshItems` just put manager specific code in `addNewItem`/`updateCachedItem`/`removeCachedItem` if necessary
- Spread refresh calls by appropriate constructors
- Used `Permission` class also for retrieving permissions from database
- Do not think we will use common function `executeMapQuery` in near …
=> Few managers optimizations

src/org/traccar/database/DataManager.java, src/org/traccar/database/DeviceManager.java, src/org/traccar/database/DriversManager.java, src/org/traccar/database/UsersManager.java
fix for https://www.traccar.org/forums/topic/build-source-code-error/
This maps might be not initialized if objects list is empty, but called `getXxxByUniqueId` function.
=> Initialize some maps, because they might be accessed before initialized.

src/org/traccar/Context.java, src/org/traccar/api/BaseObjectResource.java, src/org/traccar/api/resource/AttributeResource.java, src/org/traccar/api/resource/CalendarResource.java, src/org/traccar/api/resource/DeviceResource.java, src/org/traccar/api/resource/DriverResource.java, src/org/traccar/api/resource/GeofenceResource.java, src/org/traccar/api/resource/GroupResource.java, src/org/traccar/api/resource/UserResource.java
Implemented generic `BaseObjectResource` and combined all checks and updates in 3 functions.
They look rather complex, but really simple:
- Check before action
- Action: add/update/remove
- Refresh after action
Leaved `add` in users resource as is because it is too different.
I'm not very satisfied with `getManagers` function because of unchecked type casting warning, but it works correctly.
`@GET` functions not optimized for now, set of parameters and logic are different. Probably I'll implement some intermediate subclasses with common GET functions for `SimpleObjectManager`s and for `ExtendedObjectManager`s. They look similar.
=> Combine PUT/POST/DELETE functions in object resources

src/org/traccar/api/BaseObjectResource.java, src/org/traccar/api/ExtendedObjectResource.java, src/org/traccar/api/SimpleObjectResource.java, src/org/traccar/api/resource/AttributeResource.java, src/org/traccar/api/resource/CalendarResource.java, src/org/traccar/api/resource/DriverResource.java, src/org/traccar/api/resource/GeofenceResource.java, src/org/traccar/api/resource/GroupResource.java
Put `getSimpleManagerItems` function to Base because it is impossible make strict inheritance Base->Simple->Extended because it is impossible override `@GET` and `get` with different set of parameters.
`ManagableObjects` interface become useful.
=> Combine some GET functions

src/org/traccar/database/DriversManager.java, src/org/traccar/database/UsersManager.java
There was a `NullPointerException` if we try to get object by unknown uniqueId or token.
I suppose there is no difference what to map String->Long or String->User, these are only links.
Replaced map to objects itself and now we correctly get `null` in `getByXXX` functions without additional checks. Also it is consistent with `DeviceManager`
=> Fix retrieving objects by unknown tokens/uniqueId

src/org/traccar/database/DataManager.java
Two fixes:
- IF condition was wrong, log record was made if `query != null`. fixed that
- noticed incorrect table name construction
````
2017-08-02 00:10:12  WARN: Table 'traccar.statisticss' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:477 < DataManager:445 < StatisticsManager:64 < ...)
````
There was two options: correct table name construction or rename `Statistics` to `Statistic` for consistence, decide first one. If it is better second, i'm ready to rename.
=> Avoid unneeded log record and fix table name constructions

src/org/traccar/notification/NotificationMail.java
fix #3417 
We do not need it, because it automatically enabled if username and password provided.
=> Remove "mail.smtp.auth" parameter

src/org/traccar/BasePipelineFactory.java, src/org/traccar/Context.java, src/org/traccar/database/ConnectionManager.java, src/org/traccar/database/DeviceManager.java, src/org/traccar/events/MotionEventHandler.java, src/org/traccar/events/OverspeedEventHandler.java, src/org/traccar/model/DeviceState.java, src/org/traccar/reports/ReportUtils.java, src/org/traccar/reports/Stops.java, src/org/traccar/reports/Trips.java, test/org/traccar/events/MotionEventHandlerTest.java, test/org/traccar/events/OverspeedEventHandlerTest.java
Implementation is simpler than motion because there is no "not-overspeed" event.
Logic stayed the same, but with delay. For example:
`minimalDuration = 15 seconds`, but device "overspeeding"  for a minute, if `notRepeat = false`  about 4 events will be generated (if reported with enough frequency) if `notRepeat = true` - only one event.
Also made a few small optimizations with previous code.
- Initialize `DeviceState` in get method
- Unwrapped some not obvious nested checks
=> Implement delayed overspeed events

src/org/traccar/BaseEventHandler.java, src/org/traccar/database/ConnectionManager.java, src/org/traccar/database/NotificationManager.java, src/org/traccar/events/AlertEventHandler.java, src/org/traccar/events/CommandResultEventHandler.java, src/org/traccar/events/DriverEventHandler.java, src/org/traccar/events/FuelDropEventHandler.java, src/org/traccar/events/GeofenceEventHandler.java, src/org/traccar/events/IgnitionEventHandler.java, src/org/traccar/events/MaintenanceEventHandler.java, src/org/traccar/events/MotionEventHandler.java, src/org/traccar/events/OverspeedEventHandler.java, src/org/traccar/reports/ReportUtils.java, test/org/traccar/events/AlertEventHandlerTest.java, test/org/traccar/events/CommandResultEventHandlerTest.java, test/org/traccar/events/IgnitionEventHandlerTest.java, test/org/traccar/events/MotionEventHandlerTest.java, test/org/traccar/events/OverspeedEventHandlerTest.java
Totally slip out of mind, we also have to load old position to map it to notification like we do on web side.
It might be looking like quickfix, if you are totally against requesting DB here I have a couple of ideas:
- Simply cache such delayed positions (map `positionId`->`Position` but I do not know when cleanup them, some positions might be related more than one event)
- Rethink how we call event handlers, now, they basically inside separate pipeline handlers. We can implement common pipeline handler to call all event handlers, collect results and call notification once. Because `DeviceState` has cached related position we can pass them to notification and avoid additional DB requests.
Also fixed nested condition
=> Map correct position to delayed event notification

src/org/traccar/reports/ReportUtils.java, test/org/traccar/reports/ReportUtilsTest.java
Testing trips detector on real data noticed a couple of problems:
- In case `deviceState` switched instantly in one position (stopped and switched ignition off) we missed it
- Fluctuations of opposite state incorrectly handled (did not reset `startEventIndex`)
Added appropriate tests
=> Fix trips and stops detector

src/org/traccar/FilterHandler.java, test/org/traccar/FilterHandlerTest.java
Some protocols report alarms without coordinates, we use last position to construct new one. Such position very likely will be filtered (if filter enabled)
Implemented configuration parameter to skip such positions (not filter)
Parameter name is controversial.
Also fixed http://findbugs.sourceforge.net/bugDescriptions.html#ICAST_IDIV_CAST_TO_DOUBLE
=> Do not filter alarms

src/org/traccar/protocol/Gt06ProtocolDecoder.java, test/org/traccar/protocol/Gt06ProtocolDecoderTest.java
Skipbyte 8 is correct for location data. But for alarm packet it is 9. Also alarm data is after LBS, due to which it is giving wrong alarms and it needs to be changed to skipbyte 9 as it was previously.
Also, some gt06 devices sending GPS information length 13 instead of 12, so I have added length to maximum 12 incase it is greater than 12.
Status packet is sending 13 length for GPS information. But as per protocol document, it cannot be greater than 12.
Example Login Packet
```
78780d01035873507021706101314f600d0a
```
Status Packet
```
78782516110819110208d402f264dc08289a4058d4c70901944600d300c0954606040600014057e90d0a
```
Due to above issue, it is sending alarm power cut as LBS data is skipping one extra value due to which it is taking language which is 02 and 02 is also for power cut. …
=> GT06 alarm packet issue

src/org/traccar/BaseProtocolDecoder.java, src/org/traccar/protocol/OsmAndProtocolDecoder.java, src/org/traccar/protocol/Tk103ProtocolDecoder.java, src/org/traccar/protocol/XexunProtocolDecoder.java
It is not obvious but looks like OsmAnd application post speed in m/s units http://osmand.net/features?id=trip-recording-plugin#Online_tracking , but Traccar Client uses knots.
I think it is good idea to make it configurable, at least server wide.
Also fix #3487
=> Make OsmAnd speed units configurable

src/org/traccar/protocol/CityeasyProtocolEncoder.java, src/org/traccar/protocol/Jt600ProtocolEncoder.java, src/org/traccar/protocol/MeiligaoProtocolEncoder.java, src/org/traccar/protocol/MiniFinderProtocolEncoder.java, src/org/traccar/protocol/Pt502ProtocolEncoder.java, src/org/traccar/protocol/WatchProtocolEncoder.java, test/org/traccar/protocol/CityeasyProtocolEncoderTest.java, test/org/traccar/protocol/Jt600ProtocolEncoderTest.java, test/org/traccar/protocol/MeiligaoProtocolEncoderTest.java, test/org/traccar/protocol/MiniFinderProtocolEncoderTest.java, test/org/traccar/protocol/Pt502ProtocolEncoderTest.java, test/org/traccar/protocol/WatchProtocolEncoderTest.java
In continuous #3496  
Decided to replace how we treat `Command.KEY_TIMEZONE`. Now it is timezone id (like user/server timezone)
As about backward compatibility, i think it will be easy convert seconds to "GMT+XX:XX" if somebody use this API.
Unfortunately `TimeZone.getTimeZone()` return "GMT" not exception if passed unknown/incorrect id but I thing it is OK.
PS: Pt502 does not have any Timezone formatting, and worked incorrectly.
=> Accept timezone id instead of offset in commands

src/org/traccar/database/DeviceManager.java, src/org/traccar/model/ExtendedModel.java, src/org/traccar/notification/NotificationMail.java, src/org/traccar/notification/PropertiesProvider.java, src/org/traccar/protocol/OsmAndProtocolDecoder.java, test/org/traccar/ProtocolTest.java, test/org/traccar/protocol/OsmAndProtocolDecoderTest.java
- Moved Boolean workaround outside the `ExtendedModel`. I think it should be clean.
- Adapted `DeviceManager.lookupAttributeXxx` to handle correct and incorrect types (temporary solution, for year or so)
- Handle boolean attributes in `OsmAndProtocol`
- Handle `mail.smtp.port` as integer
Some comments in code
=> Handle correct and incorrect attribute types

src/org/traccar/FilterHandler.java, test/org/traccar/BaseTest.java, test/org/traccar/FilterHandlerTest.java
Main switch is `filter.skipAttributes.enable` because lookup might costs a lot.
Attributes list should be in `filter.skipAttributes`
fix #3513 
=> Implement skipping filtering by list of attributes

schema/changelog-3.15.xml, src/org/traccar/Context.java, src/org/traccar/api/BaseObjectResource.java, src/org/traccar/api/resource/CommandResource.java, src/org/traccar/api/resource/CommandTypeResource.java, src/org/traccar/api/resource/DeviceResource.java, src/org/traccar/api/resource/UserResource.java, src/org/traccar/database/CommandsManager.java, src/org/traccar/database/DataManager.java, src/org/traccar/database/DeviceManager.java, src/org/traccar/database/PermissionsManager.java, src/org/traccar/model/Command.java, src/org/traccar/model/Server.java, src/org/traccar/model/User.java
Main purposes of change:
- There are number of feature requests to add way to save custom commands
- I believe there were feature requests to allow users send only some commands
Implemented:
- Added boolean user/server field "Limit Commands" means "Limit sending only Saved Commands". If it is true:
- user can not edit/link/unlink Saved Commands
- user can not send not Saved Commands
- user can send already linked to him and to device Saved Commands
- Added `description` field to `Command` model to get some human readable name
- Added `CommandsManager` extending `ExtendedObjectManager`
- Moved commands related things from `DeviceManager` to `CommandsManager`
fix #3470
=> Implement Saved Commands

schema/changelog-3.15.xml, src/org/traccar/Context.java, src/org/traccar/api/BaseObjectResource.java, src/org/traccar/api/resource/CommandTypeResource.java, src/org/traccar/api/resource/NotificationResource.java, src/org/traccar/api/resource/UserResource.java, src/org/traccar/database/CommandsManager.java, src/org/traccar/database/DataManager.java, src/org/traccar/database/NotificationManager.java, src/org/traccar/database/PermissionsManager.java, src/org/traccar/model/Notification.java, src/org/traccar/model/Typed.java, swagger.json
- Made `Notification` standard objects, managed by `ExtendedObjectManager`
- Add `allways` field to Notification model, this flag means that user wants to get notification of desired type from all his devices.
- Made `Typed` class to use when we return Command Types and Notification Types
fix #2893
=> Implement per device Notifications

src/org/traccar/protocol/TeltonikaProtocolDecoder.java
Looks like it was implemented before we started handle command responses in modern way
https://github.com/tananaev/traccar/commit/17744264e2938cf8c87346c175e458cd89a1f3c6#diff-1fcc7f951825555b40d62ec37802158f
I've checked on real device, send command "getparam 800" and got this:
=> Teltonika: store command response as KEY_RESULT

src/org/traccar/notification/NotificationMail.java
Made user SMTP config more priority and added switch to ignore user config
fix #3552
=> Make user SMTP config more priority than server

setup/docker/build.sh
Docker builds were being versioned with literal '_version'
=> Fix version assignment in docker build script

src/org/traccar/api/resource/CommandResource.java, src/org/traccar/database/CommandsManager.java, src/org/traccar/model/Command.java
We can't send bare Saved Command, we need to set `deviceId` in it before sending to log working correctly. Also we can't set `deviceId` in Saved Command to not change cached instance.
I decided just override incoming entity with cached Saved Command
Also optimized resource a bit.
fix #3592 
PS: tested with a real device
=> Set deviceId in Saved Command before sending

src/org/traccar/processing/ComputedAttributesHandler.java, test/org/traccar/processing/ComputedAttributesTest.java
It would be useful to have `Math` functions in Computed Attributes. Class registered as function namespaces http://commons.apache.org/proper/commons-jexl/reference/syntax.html#Functions
https://www.traccar.org/forums/topic/power-math-operation-in-computed-attributes/
=> Map "Math" to Computed Attributes context

src/org/traccar/BasePipelineFactory.java, src/org/traccar/Context.java, src/org/traccar/GeocoderHandler.java, src/org/traccar/api/resource/ServerResource.java, src/org/traccar/geocoder/BingMapsGeocoder.java, src/org/traccar/geocoder/FactualGeocoder.java, src/org/traccar/geocoder/GeocodeFarmGeocoder.java, src/org/traccar/geocoder/Geocoder.java, src/org/traccar/geocoder/GisgraphyGeocoder.java, src/org/traccar/geocoder/GoogleGeocoder.java, src/org/traccar/geocoder/JsonGeocoder.java, src/org/traccar/geocoder/MapQuestGeocoder.java, src/org/traccar/geocoder/NominatimGeocoder.java, src/org/traccar/geocoder/OpenCageGeocoder.java, src/org/traccar/reports/ReportUtils.java, test/org/traccar/geocoder/GeocoderTest.java
In some cases it is not necessary to revers geocoding every position. It might be enough find out addresses of trips endpoints for reports and allow user check address on demand from web client.
- Moved `AddressFormat` inside `Geocoder`
- Implement synchronous geocoding
- Implement retry geocoding for trips/stops reports
- Implement API for revers geocoding
if `geocoder.enable` - `true` - it will try for all positions, if `report.retryGeocoding` - `true` it will retry find out addresses of trips and stops. If both are false, geocoder is disabled.
I have an initial implementation for web client 
more comments in code...
=> Retry geocoding for trips/stops

src/org/traccar/database/LdapProvider.java, src/org/traccar/database/NotificationManager.java
If `geocoder.onRequest` enabled retry to geocode event related position before sending notification.
Also fixed unnecessary String creation in `LdapProvider`
=> Do geocoding for every events related position

src/org/traccar/api/BaseObjectResource.java, src/org/traccar/api/resource/DeviceResource.java, src/org/traccar/api/resource/PermissionsResource.java, src/org/traccar/api/resource/ServerResource.java, src/org/traccar/api/resource/SessionResource.java, src/org/traccar/api/resource/UserResource.java, src/org/traccar/helper/LogAction.java
Here is implementation of logging user actions:
- Object create/edit/remove
- Objects link/unlink
- User login/logout
- Reset device total distance
Made it non-switchable, only with global log. I do not think log size will grow dramatically in comparing with device communications debug.
Example:
```
2017-12-13 14:48:21  INFO: User: 1, Action: login
2017-12-13 12:05:53  INFO: User: 1, Action: edit, Object: User, Id: 18
2017-12-13 12:06:27  INFO: User: 1, Action: link, Owner: User, Id: 18, Property: Group, Id: 11
2017-12-13 12:06:28  INFO: User: 1, Action: link, Owner: User, Id: 18, Property: Group, Id: 5
2017-12-13 12:06:30  INFO: User: 1, Action: unlink, Owner: User, Id: 18, Property: Group, Id: 11
2017-12-13 14:48:23  INFO: User: 1, Action: logout
2017-12-13 14:48:21  INFO: User: 2, …
```
=> Log user actions

src/org/traccar/api/BaseObjectResource.java, src/org/traccar/database/DeviceManager.java, src/org/traccar/database/GroupsManager.java
Deleting group may cause cascade clear `groupId` fields in `groups` and `devices` DB tables. We need refresh cached objects.
https://www.traccar.org/forums/topic/group-delete-issue/
=> Update group and device cache on group delete.

src/org/traccar/model/Position.java
I was not aware about the initialization of serverTime and didn't found any better way than this.
Pull Request:
https://github.com/tananaev/traccar/pull/3721
=> NPE bug fix for the Position's serverTime

schema/changelog-3.16.xml, src/org/traccar/api/BaseObjectResource.java, src/org/traccar/database/NotificationManager.java, src/org/traccar/model/Geofence.java, src/org/traccar/model/Notification.java, src/org/traccar/model/ScheduledModel.java
A calendar can be selected for a notification now. If it is selected, notification will be sent only in calendar period.
- Introduced `ScheduledModel` for objects with `calendarId` field
- Filter "effective" notifications by calendar
- Added permission check when add or update `ScheduledModel` objects (User should not be able select calendar he do not have access)
- Removing calendar can cause cascade clear of `calendarId` fields we should refresh geofences and notifications.
=> Implement scheduled notifications

src/org/traccar/smpp/ClientSmppSessionHandler.java, src/org/traccar/smpp/SmppClient.java
- More correctly distinguish delivery reports from incoming messages
Inspired https://www.traccar.org/forums/topic/sms-receiving-problem-brazil/, looks like that SMSC reports some optional parameters with ordinary messages.
- Added optional `sms.smpp.requestDrl` parameter to enable request delivery reports for all outgoing SMS
Delivery reports contain all information as text, we can log it as other messages, just not fire event. Log example:
```
2018-01-24 12:38:55 DEBUG: SMS submitted, message id: f27322e5-6f88-49e5-8c4c-2ae9dedd8dfe
2018-01-24 12:39:29 DEBUG: SMS Message Received: id:f27322e5-6f88-49e5-8c4c-2ae9dedd8dfe sub:001 dlvrd:001 submit date:1801241238 done date:1801241239 stat:DELIVRD err:000 text:     Success, Source Address: +7922xxxxxxx
2018-01-24 12:41:33 DEBUG: SMS Message …
```
=> Improve incoming SMS handling

src/org/traccar/api/MediaFilter.java, src/org/traccar/protocol/Gt06ProtocolDecoder.java, src/org/traccar/web/WebServer.java
There is a switch `media.dirAllowed` to allow access directories. Admin can enumerate root directory, users only device directories they have access.
- Added `DefaultServlet` to serve folder with media files as static content
- Added filter to check access to device
fix #3688 
More comments in code...
=> Provide web access to media files received from devices

src/org/traccar/BasePipelineFactory.java, src/org/traccar/WebDataHandler.java, test/org/traccar/WebDataHandlerTest.java
Hi Anton,
As we discussed, I added the forward.json to determine POST or GET in forward url.
=> added POST option to forward url

src/org/traccar/BaseProtocolDecoder.java, src/org/traccar/DeviceSession.java, src/org/traccar/WebDataHandler.java, src/org/traccar/notification/EventForwarder.java, src/org/traccar/protocol/Gt06ProtocolDecoder.java, src/org/traccar/protocol/UlbotechProtocolDecoder.java
Added `timeZone` field to `DeviceSession`
- It might be initialized once on login message and used in all next packets
- It might be initialized once on device session creation to not lookup all tree on every position. But to apply timezone changes device has to reconnect.
Also removed unnecessary checks in forwarders
fix #3572
=> Unified Device timezone handling

src/org/traccar/geocoder/Address.java, src/org/traccar/geocoder/AddressFormat.java, src/org/traccar/geocoder/BingMapsGeocoder.java, src/org/traccar/geocoder/GeocodeFarmGeocoder.java, src/org/traccar/geocoder/GisgraphyGeocoder.java, src/org/traccar/geocoder/GoogleGeocoder.java, src/org/traccar/geocoder/NominatimGeocoder.java, src/org/traccar/geocoder/OpenCageGeocoder.java
Most of the reverse geocoder api's provide formatted address with all the details.
This change can help users to use formatted address. As Nominatim address are not proper in address details, this can help to use formatted address directly.
Nominatim Sample:
```json
{
"place_id": "439734",
"licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
"osm_type": "way",
"osm_id": "77643464",
"lat": "28.6454569",
"lon": "77.0690221",
**"display_name": "Vikaspuri, West Delhi, Delhi, 110041, India",**
"address": {
"city_district": "Vikaspuri",
"county": "West Delhi",
"state": "Delhi",
"postcode": "110041",
"country": "India",
"country_code": "in"
},
"namedetails": {},
"boundingbox": [
"28.6348108",
"28.649576",
"77.0606304",
"77.0833674"
]
}
```
Gisgraphy:
```json
{ …
```
=> To use formatted address directly instead of creating address.

src/org/traccar/database/GroupsManager.java
Cycle in group hierarchy check only works during cache update but not checking at the time of entry updation into the DB.
=> Cycle in group hierarchy bug fix while editing Groups

src/org/traccar/database/NotificationManager.java, src/org/traccar/notification/EventForwarder.java, src/org/traccar/notification/JsonTypeEventForwarder.java, src/org/traccar/notification/MultiPartEventForwarder.java
This change will allow to make traccar integration a bit more simpler 
The set of users is the same as traccar uses to notify about forwarded Event.
fix #3814
=> Add user objects to Event forward payload

src/org/traccar/smpp/SmppClient.java
Send long messages as "message_payload". It should be supported by most current SMSCs.
Implementing true "MultiSubmitSm" will over-complicate code and I believe really not necessary nowadays.
Tested with my kannel test smpp.
fix #3818
=> Add support for long SMS sending

setup/default.xml, src/org/traccar/Context.java, src/org/traccar/database/CommandsManager.java
There is a reason to make it switchable.
Leaved it enabled in `default.xml`
fix #3861
=> Make Commands queueing switchable

src/org/traccar/protocol/Gl200TextProtocolDecoder.java, src/org/traccar/protocol/GoSafeProtocolDecoder.java, test/org/traccar/ProtocolTest.java
First step for #3532 
Implemented parsing engine hours in GoSafe and similar GL200.
Have not noticed any tests with missed minutes and seconds in GL200 but implemented like in GoSafe, just in case.
=> Store engine hours in GL200 and GoSafe in milliseconds

src/org/traccar/helper/UnitsConverter.java, src/org/traccar/protocol/AplicomProtocolDecoder.java, src/org/traccar/protocol/AstraProtocolDecoder.java, src/org/traccar/protocol/ContinentalProtocolDecoder.java, src/org/traccar/protocol/Gl200TextProtocolDecoder.java, src/org/traccar/protocol/Gps103ProtocolDecoder.java, src/org/traccar/protocol/Mta6ProtocolDecoder.java, src/org/traccar/protocol/MxtProtocolDecoder.java, src/org/traccar/protocol/SuntechProtocolDecoder.java, src/org/traccar/protocol/VtfmsProtocolDecoder.java, src/org/traccar/protocol/XirgoProtocolDecoder.java
Next step for #3532 
Assumed that most of protocol reports in hours.
=> Store engine hours in milliseconds for the rest of protocols

setup/default.xml, src/org/traccar/BasePipelineFactory.java, src/org/traccar/EngineHoursHandler.java, src/org/traccar/reports/ReportUtils.java, src/org/traccar/reports/Summary.java
I believe it is final server side step for #3532 
Main switch is `engineHours.enable` it controls two features:
- Enable `EngineHoursHandler` itself
- Enable engine hours calculation in reports (I think if switch is disabled user do not interested in engine hours at all, we just will not waste time on calculating it)
Handler designed as if device have never reported `hours` or `ignition` attribute will never appear.
Also it works as `copyAttributes` if device reports `hours` not in every position.
One side effect, if device reports `hours` periodically, traccar will still accumulate `hours` in between.
Some comments in code...
=> Implement engine hours accumulation

schema/changelog-4.0.xml, schema/changelog-master.xml, setup/default.xml, src/org/traccar/database/DataManager.java, test/org/traccar/database/DataManagerTest.java
I think it is right to detach renaming to separate changeset with precondition, can't say why but feel it is better.
=> Rename all tables to avoid using reserved words

src/org/traccar/events/OverspeedEventHandler.java
`geofenceIds` might be null for new device
=> Fix OverspeedEventHandler with new device

src/org/traccar/database/ConnectionManager.java
You are right, we should not lock to active device adding/removing.
It is fine if we send queued commands when device become online.
There is no good way to determine if udp device on other side, just try to send command to "unknown" device.
I think we can add switch with logic like "queue commands if device status unknown" in future if there will be requests from users.
=> Send queued commands on status online

src/org/traccar/protocol/OsmAndProtocolDecoder.java
I added a check for 0 or 1, because the `&valid=1`.
Now it will set the valid correct in this case also...
=> Added integer checking for valid in osmand

schema/changelog-4.0.xml
Made separate migrations for h2, mysql, mssql(`common`) and postgresql (`pg`).
Split on `pre`, "main" and `post`.
Added preconditions in case somebody already successfully migrated to 4.0 for future.
It might looks a bit complicated but I hope be universal.
fix #3993
=> Fix for notifications migration on postgresql and mssql

setup/package.sh
Rationale: Religion forbids me to build anything for a proprietary OS.
```
$ ./platform.sh
Usage: ./platform.sh VERSION [PLATFORM]
Build Traccar installers.
Without PLATFORM provided, builds installers for all platforms.
Available platforms:
* linux-x64
* linux-arm
* windows-64
* other
```
Should be fairly easy to understand. Fancy colors for clueless people.
Caveats:
* Only tested twice.
* Will not run on a PDP-11.
=> package.sh revisited

src/org/traccar/geocoder/OpenCageGeocoder.java
This makes the response slightly faster by not requesting information traccar never uses.
See:
https://opencagedata.com/api#bestpractices
https://opencagedata.com/api#forward-opt
=> Add no_annotations=1 parameter in the call to OpenCage API

schema/changelog-4.0-clean.xml
Fixed triggers in MSSQL after renaming columns.
Tested migrations 4.0 to current and clean current.
They should be done as separate SQLs because "CREATE TRIGGER needs to be the first in a batch"
=> Fix MSSQL triggers after renaming columns

src/org/traccar/Context.java, src/org/traccar/geocoder/MapmyIndiaGeocoder.java, test/org/traccar/geocoder/GeocoderTest.java
@tananaev request you to kindly review the changes and merge them if you find it OK.
MapmyIndia reverse geocoding is very helpful for the Indian
subcontinent, It's "distance from nearest POI" detail embedded in the
formatted_address field of the response is quite impressive for the
reports.
The Confirgurations required to be added in the config file
"traccar.xml" are
<entry key='geocoder.enable'>true</entry>
<entry key='geocoder.type'>mapmyindia</entry>
<entry key="geocoder.url">https://apis.mapmyindia.com/advancedmaps/v1</entry>
<entry key="geocoder.key">YOUR_KeY</entry>
<entry key="geocoder.format">%f</entry>
Signed-off-by: Syed Mujeer Hashmi <mujeerhashmi@gmail.com>
=> geocoder: Implement MapmyIndia Reverse geocoder

src/org/traccar/sms/HttpSmsClient.java
Hi @tananaev ,
The authorization header may require different name:value pair for
specifying token by the service provider. Add a config parameter
"sms.http.authorizationName" to support this. In case of msg91, the
name required is "authkey".
The newline at the end of short templates are causing invalid json in
request. Get rid of the newline using trim().
The required config to enable msg91 sms notifications are
<entry key='notificator.types'>web,mail,sms</entry>
<entry key='notificator.sms.manager.class'>org.traccar.sms.HttpSmsClient</entry>
<entry key='sms.http.url'>http://api.msg91.com/api/v2/sendsms</entry>
<entry key="sms.http.authorizationName">authkey</entry>
<entry key='sms.http.authorization'>[YOUR TOKEN]</entry>
<entry key='sms.http.template'>
{
"sender": "SOCKET",
"route": …
=> SMS client: Changes to support msg91

src/org/traccar/events/GeofenceEventHandler.java
If the position simultaneously generates an exit from the previous geofence and an entrance to the next one, then we will get an incorrect sequence of events. I think that in this case the geofenceExit event should be before the geofenceEnter event.
Example: [report.xlsx](https://github.com/traccar/traccar/files/2866664/report.xlsx)
=> Fixed geofences processing order

src/main/java/org/traccar/config/Keys.java
Hello
- Fixed `coordinates.maxError` key string
- Improved `coordinates.filter` description
=> Fix coordinates.maxError key and coordinates.filter description

src/main/java/org/traccar/handler/GeolocationHandler.java
We losing data from device when location captured via geoservices.
=> Fix, rssi info is deleting when locations get from geolocation services

src/main/java/org/traccar/BaseProtocolDecoder.java, src/main/java/org/traccar/model/Position.java, src/main/java/org/traccar/protocol/LaipacProtocolDecoder.java, src/test/java/org/traccar/protocol/LaipacProtocolDecoderTest.java
Extending Laipac protocol decoder to handle EAVSYS messages. These type of sentences can be used to get the hardware type, the firmware version and the SIM card ICCID. Tell me if you have a better idea for the first commit. Thanks.
=> Enhance Laipac protocol decoder (2)

src/main/java/org/traccar/BaseProtocolDecoder.java, src/main/java/org/traccar/database/ConnectionManager.java, src/main/java/org/traccar/database/DeviceManager.java, src/main/java/org/traccar/database/IdentityManager.java, src/main/java/org/traccar/handler/CopyAttributesHandler.java, src/main/java/org/traccar/handler/FilterHandler.java, src/main/java/org/traccar/handler/events/FuelDropEventHandler.java, src/main/java/org/traccar/handler/events/OverspeedEventHandler.java, src/main/java/org/traccar/protocol/Gt06ProtocolEncoder.java, src/main/java/org/traccar/protocol/H02ProtocolEncoder.java, src/main/java/org/traccar/protocol/HuabaoProtocolEncoder.java, src/main/java/org/traccar/protocol/MeitrackProtocolEncoder.java, src/main/java/org/traccar/protocol/SuntechProtocolDecoder.java, src/main/java/org/traccar/protocol/T55ProtocolDecoder.java, src/main/java/org/traccar/protocol/Tk103ProtocolEncoder.java, src/main/java/org/traccar/reports/Stops.java, src/main/java/org/traccar/reports/Summary.java, src/main/java/org/traccar/reports/Trips.java, src/test/java/org/traccar/TestIdentityManager.java
Make optional the server-wide attributes lookup. It's already avoided when a lookup up is performed on the configuration file, I'm keeping it that way...
=> Make optional server attributes lookup

setup/default.xml, src/main/java/org/traccar/protocol/LeafSpyProtocol.java, src/main/java/org/traccar/protocol/LeafSpyProtocolDecoder.java, src/test/java/org/traccar/protocol/LeafSpyProtocolDecoderTest.java
This PR adds a protocol and decoder to decode the live data that can be sent from the [LeafSpy Pro](http://www.electricvehiclewiki.com/wiki/leaf-spy-pro/) application which pulls information from the OBD port of a Nissan Leaf.
=> Add leafspy app protocol and decoder

src/main/java/org/traccar/protocol/WialonProtocol.java, src/main/java/org/traccar/protocol/WialonProtocolDecoder.java, src/test/java/org/traccar/protocol/WialonProtocolDecoderTest.java
Enhancing Wialon protocol decoder, mainly extending it according to specifications to decode messages carrying the device id, allowing to:
- Use UDP protocol as transport
- Receive messages for multiple devices using the same TCP connection (of course, disabling session cache for the protocol)
Waiting for comments...
Thanks a lot
=> Enhance Wialon protocol decoder

src/main/java/org/traccar/protocol/Gt06ProtocolDecoder.java, src/test/java/org/traccar/protocol/Gt06ProtocolDecoderTest.java
Adds JC100 camera alarms as described in [document](https://www.dropbox.com/s/gysbq0mgugri01u/20170830%20Communication%20Protocol%20of%20JC100.pdf?dl=0), linked from a [traccar support forum topic](https://www.traccar.org/forums/topic/jc100-image-and-video-protocol/).
The camera communicates using *gt06* protocol but the alerts differ from what has been already implemented in `Gt06ProtocolDecoder` in traccar server.
=> Adds JC100 camera alarms

swagger.json
Refer to this [post](https://www.traccar.org/forums/topic/does-position-model-needs-correction/) for discussion.
=> swagger: Fix type's to avoid deserialize issues.

src/main/java/org/traccar/MainModule.java, src/main/java/org/traccar/WebDataHandler.java, src/main/java/org/traccar/config/Keys.java
Added an optional (configurable) queue, actually a ring buffer, to forwarded positions in web data handler. The size of the queue can be specified in the configuration file. If the queue is enabled, HTTP responses needs to be 200 OK to get positions removed from the queue. I'm planning to do the same with event forwarding.
Waiting for comments...
Thanks.
=> Add an optional queue to web data handler

src/main/java/org/traccar/notification/NotificatorManager.java, src/main/java/org/traccar/notificators/NotificatorPushover.java
add four new traccar.xml entries:
notificator.pushover.token  // (required) token from pushover.net
notificator.pushover.user // (required) user from pushover.net
notificator.pushover.device // optional: your user's device name to send the message directly to that device, rather than all of the user's devices (multiple devices may be separated by a comma)
notificator.pushover.title // optional: your message's title, otherwise your app's name is used
=> add support for pushover.net

src/main/java/org/traccar/database/BaseObjectManager.java
Noticed that if you use the id parameter and pass an item  that does not exist null items are also returned in the response array when enriching devices. This PR ensures an item is not null before adding into the collection
=> Ensure item is not null before adding to the collection  in getItems

src/main/java/org/traccar/protocol/FreematicsProtocolDecoder.java
Added support for standard PIDs returned by Freematics firmware. Prefixed all other PID attributes to maintain compatibility with JEXL.
=> Update Freematics API

src/main/java/org/traccar/protocol/TeltonikaProtocolDecoder.java
Teltonika protocol - change fuel level from io89 (in percents) to io84 (in litres). 
Io84 this is a fuel in litres * 0.1
https://wiki.teltonika-gps.com/view/FMB_AVL_ID
=> Teltonika protocol - change fuel level from io89 to io84

src/main/java/org/traccar/protocol/TeltonikaProtocolDecoder.java
Teltonika protocol:
changed  Ecodriving from io238 to io253.
removed io237.
=> Teltonika protocol - change Ecodriving io and movement

src/main/java/org/traccar/protocol/TeltonikaProtocolDecoder.java
Codec12 and codec13 uses no ACK at all. I modified TeltonikaProtocolDecoder.java to avoid sending ACK on those specific codecs.  This issue raised an error "[D.P.TCP]-> CODEC12 ERROR in state 0, ZEROES MISSING" on the gps device log. Tested with FM6300 and FMU125. 
https://wiki.teltonika-gps.com/view/Codec#Codec_12
=> [Teltonika] Fix wrong ACK on codec 12 and 13

setup/package.sh
Current versions of makeself on linux can check if the user running the final self extracting installer is root. When not it will show a warning.
This update adds this options to the makeself command.
This option was added to makeself in december 2016 ([commit on github](https://github.com/megastep/makeself/commit/436cf306fe05ab4d4805d3fda69660faac8eb4a5#diff-12513486c9b5ce3dea36337159a0fa4f62ca8044c68221ba206e163e630e25a6)) and is available on ubuntu 18.04.
=> As the installation needs root permissions beter check the user is root

setup/setup.sh
When you update an existing traccar installation with the standard installer it will overwrite an existing "traccar.xml" config file. 
As this file is used for local changes to your installation you currently have to manually copy it aside before running the update. And restore it after the update.
This change will preserve the existing "traccar.xml" when it finds one and stores the new "traccar.xml" template from the installer as "traccar.xml.new".
=> Preserve existing traccar.xml on update

.github/workflows/gradle.yml
Adds the CLI option `--warning-mode=fail` to the Gradle build job. This ensures the build only passes if no warnings are cast.
See: https://docs.gradle.org/current/userguide/command_line_interface.html#sec:command_line_warnings
=> CI: Only pass if there are no Gradle warnings

src/main/java/org/traccar/handler/CopyAttributesHandler.java
Why are we forcing KEY_DRIVER_UNIQUE_ID on copyAttributes?
Also, if exists why should it be duplicated?
=> KEY_DRIVER_UNIQUE_ID is hardcoded on copyAttributes

src/main/java/org/traccar/notificators/NotificatorTelegram.java
1. I decided it would be very convenient, if Telegram bots would send location native to Telegram chats.
2. Also, I think users would benefit if bot sent full message instead on short one. It shouldn't be that short as Firebase notification. (There I forgot to add `getBody()` to the code to convert to string.)
What do you think, @tananaev ?
=> Support native location messages for Telegram

src/main/java/org/traccar/protocol/WatchProtocolDecoder.java
"Steps" counter value is currently parsed from a complete GPS frame only, but according to the protocol it is also transmitted in all "LK" keepalive frames, as well as the battery level.
Example :
`[3G*123456789*000D*LK,12345,0,98]
`means 12345 steps counted and 98% battery level.
Note : for this value to be incremented, the device should receive a 'PEDO,1' command (and 'PEDO,0' to stop the counter)
=> Take "steps" value from LK frames in Watch protocol

src/main/java/org/traccar/geocoder/JsonGeocoder.java
When a service is down (like positionstack recently often is), it might send a 503 Service Unavailable which is not covered by a ClientErrorException. Using the superclass of this, will enable the position to be handled correctly still.
=> Catch all webexceptions in JsonGeocoder

setup/default.xml, src/main/java/org/traccar/config/Keys.java, src/main/java/org/traccar/database/DataManager.java, src/main/java/org/traccar/handler/FilterHandler.java
This PR tries to address problem #4735.
=> Add support for relative filtering

tools/gen_config_doc.py
ref: https://github.com/traccar/traccar/pull/4786#issuecomment-1003489111
Left the html generation as before. I tested the pug output on an online compiler. Seemed okay.
=> feat: generate config keys as pug

src/main/java/org/traccar/protocol/WatchProtocolDecoder.java
Some 2G devices send a 00004000 code when the device is removed from its charger. This is very useful as many cheap devices have a strange magnet connector which is very easy to unplug by accident. If not working, the feature might have to be activated by sending AON,1# to the device. Does NOT work on 4G devices which send a "sos" alert in that situation (00010000).
=> Add an alarm code on Watch protocol

src/main/java/org/traccar/handler/FilterHandler.java
the skipAttributes  and skiplimit  checks was ok up to 4.14 ver. but it was removed accidentally in ver 4.15.
=> add skiplimit and skipAttributes checks for Duplicate filter again

src/main/java/org/traccar/protocol/TotemProtocol.java, src/main/java/org/traccar/protocol/TotemProtocolEncoder.java, src/main/java/org/traccar/protocol/TotemProtocolSmsEncoder.java, src/test/java/org/traccar/protocol/TotemProtocolEncoderTest.java
As mentioned in PR #4787 (also contains protocol documentation) I tried my hand at implementing SMS and GPRS commands for the Totem protocol. 
It's not yet finished, still have to test it on real devices, but basic tests look OK. I opened this pull request as I'm not proficient Java developer and am seeking feedback on code/organization. As the base format between modes is quite similar, I organized it so that the actual command get build only in one place, and then formatted for SMS or GPRS sending.
I know you are probably very busy, so I would like to thank you for taking time to review this.
=> Totem - basic support for SMS and GPRS commands

src/main/java/org/traccar/protocol/TrvProtocolDecoder.java, src/test/java/org/traccar/protocol/TrvProtocolDecoderTest.java
Hi,
this pull requests adds support for the 1903 protocol devices.
There are 3 simples changes:
- I had to allow more matches for (unused) fields in the otherwise perfectly fitting PATTERN. Strictly according to the 1903 protocol specification.
- allowed "YP14" as new condition to be parsed as position information
- added a test for a YP14 message
Regards
=> Added support for YP14 from "1903" protocol specification

src/main/java/org/traccar/MainModule.java, src/main/java/org/traccar/geocoder/OpenCageGeocoder.java, src/test/java/org/traccar/geocoder/GeocoderTest.java
follows the same logic as Nominatim which also accepts a language param to allow user to see response in their language
=> pass language param to OpenCage Geocoder

src/main/java/org/traccar/notificators/NotificatorPushover.java
The Pushover integration doesn't allow messages to be delivered per-user,
since the `NOTIFICATOR_PUSHOVER_USER` config is single for the whole instance.
=> Adds Pushover user attributes

src/main/java/org/traccar/protocol/HuabaoProtocolDecoder.java
From CC888 protocol (http://www.999gps.org/protocol/CC888_EZcarsharing_T-Box_Communication_Protocol-V5.2-20200104.pdf)
When vehicle engine is OFF, the device will stop uploading location information to platform server, it will send heart beat message to platform server every 2 minutes, the heart beat message ID is 0x0506, the message body of heart beat message is empty. The platform will reply device with general replay message ID 0x8001
=> Huabao Protocol: Add CC888 heartbeat packet

src/main/java/org/traccar/handler/events/MaintenanceEventHandler.java, src/test/java/org/traccar/handler/events/MaintenanceEventHandlerTest.java
According to the documentation:
> Traccar generates event every time totalDistance attribute gets over maintenance.start + maintenance.interval * N value where N is a natural number.
> 
> Example:
> maintenance.start=6000000, maintenance.interval=8000000
> 
> Events will be generated when totalDistance goes over 6000 km, 14000 km, 22000 km and so on.
The formula isn't coherent with the example because 0 is not a natural number. But the formula is correctly implemented, so, the event **won't be fired** when it goes over 6000 km. This the first bug.
If maintenance.interval < maintenance.start  and maintenance.start is multiple of maintenance.interval then the event will be fired before maintenance.start because the comparison will be on negative numbers. 
Another solution would be to use …
=> 2 Bugs on maintenance

build.gradle, src/main/java/org/traccar/MainModule.java, src/main/java/org/traccar/forward/EventForwarderMqtt.java
Rework of #4994 
Config:
<entry key='event.forward.type'>mqtt</entry>
<entry key='event.forward.url'>mqtt://user:pass@mqtt.example.com:1883</entry>
<entry key='event.forward.topic'>traccar/events</entry>
=> MQTT EventForwarder added

src/main/java/org/traccar/protocol/Tlt2hProtocolDecoder.java, src/test/java/org/traccar/protocol/Tlt2hProtocolDecoderTest.java
This branch adds LBS support for tlt2h protocol.
According to [this protocol](https://www.mictrack.com/downloads/protocols/Mictrack_Communication_Protocol_For_MT700_V1.0.pdf) there is also LBS data available in the packet if this is enabled in the device.
The docs mentions, this LBS data is an optional part of data packet, if it is enabled then it would be provided both in GPS and WiFi packets.
=> Lbs for tlt2h

.gitignore
The `bin` folder is generated by `Extension Pack for Java` in `VS Code`.
The `.vscode` folder is generated by `VS Code` directly.
These are generated in the development environment, ignoring them helps keep the git tree clean.
=> Append items in gitignore for VSCode

src/main/java/org/traccar/config/Keys.java, src/main/java/org/traccar/handler/ComputedAttributesHandler.java
Following https://github.com/traccar/traccar/issues/5028, this PR adds various preferences options to extend or disable JEXL functionality on-demand. The parser now runs in the JEXL Sandbox, which should stop most, if not any, RCE attacks. The following configuration lines were added:
- `processing.computedAttributes.parser.annotation` - if disabled, using `@annotation` constructs will result in an exception
- `processing.computedAttributes.parser.arrayReferences` - if disabled, using 'obj[ ref ]' where ref is not a string or integer literal will result in a parsing exception;
- `processing.computedAttributes.parser.lambda` - enable lambda declaration
- `processing.computedAttributes.parser.lexical` - with this on, redefining local variables will result in an exception
- …
=> Implement JEXL parser settings

src/main/java/org/traccar/api/resource/SessionResource.java
Upto yet, only admins are able to retreive session information for other users.
With this change, the managers will be also able to retreive session information for the users they manage them.
=> changed-session-retreival-permission-to-manager

src/main/java/org/traccar/api/security/LoginService.java, src/main/java/org/traccar/config/Keys.java, src/main/java/org/traccar/database/OpenIdProvider.java
Including anything I come across whilst preparing documentation (work in progress).
I think its sensible to require the openid, profile and email scopes as:
- openid - required
- email - we're mapping to accounts based on email! Aside: We should maybe look into using the 'sub' token in the future, and perhaps tie that in with storing the LDAP DN (I think they're analogous),
- profile - its useful to know the users name
Although my local SSO service (Authelia) supports groups and it seems like enterprise directories like Okta do too, public providers like Google seem not to, which does makes sense.
=> Minor tweaks to OpenID Connect integration

src/main/java/org/traccar/api/BaseObjectResource.java
This pull request allows creating objects (maintenance, geofence, notification) using the web.serviceAccountToken, this is useful in case of scripts that would for example create default maintenance, geofences and notifications for newly created users.
Resources are create without any link to a user, the script can then call api/permissions to link those resources to a given user.
=> do not add permission if user is serviceAccount

src/main/java/org/traccar/protocol/TeltonikaProtocolDecoder.java
I saw that someone made some changes to TeltonikaProtocolDecoder recently but I think Battery Level on io113 for FMBXXX was missed out.
Documentation: [https://wiki.teltonika-gps.com/view/FMC130_Teltonika_Data_Sending_Parameters_ID](https://wiki.teltonika-gps.com/view/FMC130_Teltonika_Data_Sending_Parameters_ID)
=> added Battery Level as IO 113 in TeltonikaProtocolDecoder.java

src/main/java/org/traccar/reports/RouteReportProvider.java
[fix] Excel limitation workaround for duplicate Sheets names
[Forum discussion](https://www.traccar.org/forums/topic/report-route-if-there-are-duplicate-device-names/)
[Expected result](https://github.com/traccar/traccar/files/11714435/report-110623135938.xlsx)
Declaring uniqueSheetsTitle
Add private method getUniqueSheetName
Usage in getExcel sheetNames
=> Add increment value attribute on Duplicate Device Name for Route Report.

src/main/java/org/traccar/protocol/RuptelaProtocolDecoder.java
Hi,
Ruptela IO List: [FMIO list.xlsx](https://doc.ruptela.com/resources/Storage/FMIO%20List/FMIO%20list.xlsx)
I want to update the Ruptela Protocol decoder with more data from the official FMIO list. First commit is a basic implementation of Odometer, OBD Odometer and OBD Speed -> which put me in a bit of a dilemma. Odometer and OBD Odometer map cleanly to the existing Position KEYs, but there are several possible IO Attributes that could map for OBD Speed for example. I currently took the one from the same group as OBD Odometer, as this looked the more sane option. But IO "165  - TCO Vehicle Speed" could also map into this KEY and "176 - GPS speed" too and "210 - CAN wheel based speed" and so on. What would be the best here? Do we completely avoid setting KEY_OBD_SPEED? This is just an …
=> Ruptela IO decoding for Odometer, OBD Odometer and OBD Speed

src/main/java/org/traccar/protocol/RuptelaProtocolDecoder.java
Hi,
another set of Ruptela IO improvements that builds upon https://github.com/traccar/traccar/pull/5113.
Main motivation was that I missed the IGNITION decoding. Previous implementation was rather simplistic, as different Ruptela devices have different "designated" ignition inputs now (it might be that in the past all of them were at DIN4) and the possibility of defining custom ignition logic (eg. which input is actual ignition & other possibilities).  I'm always vary of changing stuff that could break ignition decoding for some setups (eg. where the device does not have custom ignition defined and only relies on DIN4 being the ignition) - but on the other hand, without this change it absolutely breaks (at least some) properly configured Ruptela devices. Anyone affected could still use …
=> Ruptela IO Decoding improvements

src/main/java/org/traccar/protocol/RuptelaProtocolDecoder.java
Hi,
as I encountered problems with ComputedAttributes (https://github.com/traccar/traccar/issues/5116) I figured out that it'll be easier to extend the Ruptela Protocol Decoder than get ComputedAttributes working like I need it to (but the plan is to return to that). BLE Beacon ID decoding was tested locally, TCO Driver will be tested soon-ish - but from research and mock testing with the data I have, the implementation should work the same as the previous driver one and I'm highly confident that it's ok.
I'm sorry that I'm spamming this PRs, but this one should be the last for some time, and next Ruptela Decoder improvements will be a bigger PR all in one.
=> Ruptela Decoder for TCO Driver ID and BLE Beacon ID

src/main/java/org/traccar/protocol/RuptelaProtocolDecoder.java
Hi,
since some time I have noticed strange behavior on some Ruptela devices, where seemingly IOs were not sent to the server. After some digging I found out that in fact - device was sending two records, and I was just seeing the last one. After some digging in the documentation I found out that this is called Extended protocol extended messages merging, as Ruptela devices are sending more records with the same header if it cannot fit all the IOs in a single one. 
Documentation: [Ruptela Protocol 1.67](https://pdfcoffee.com/ruptela-protocol-v167pdf-4-pdf-free.html) page 15, heading "2.4 Extended protocol extended records".
I have been running this in limited testing on my staging setup and it looks good. I added the (hopefully) redundant time check, just to be more sure we are not merging …
=> Ruptela Decoder - implement Extended protocol extended messages merging

build.gradle, src/main/java/org/traccar/MainModule.java, src/main/java/org/traccar/config/Keys.java, src/main/java/org/traccar/forward/AmqpClient.java, src/main/java/org/traccar/forward/EventForwarderAmqp.java, src/main/java/org/traccar/forward/PositionForwarderAmqp.java
Add support to forward events and positions to AMQP (RabbitMQ).
Config:
```xml
<entry key="forward.url">amqp://guest:guest@localhost:5672</entry>
<entry key="forward.type">amqp</entry>
<entry key="forward.exchange">traccar</entry>
<entry key="forward.topic">positions</entry>
<entry key="event.forward.url">amqp://guest:guest@localhost:5672</entry>
<entry key="event.forward.type">amqp</entry>
<entry key="event.forward.exchange">traccar</entry>
<entry key="event.forward.topic">events</entry>
```
=> Add AMQP(RabbitMQ) Forwarder

src/main/java/org/traccar/forward/AmqpClient.java
Currently, the AMQP connection is being closed after the completion of block execution.
I made a mistake in my last PR #5136.
=> fix: AMQP auto close connection

src/main/java/org/traccar/session/state/OverspeedProcessor.java
Fixes #5103 
As soon as a speed limit is broken, an overspeed event is thrown. Current functionality waits until the 2nd reading of the overspeed instance before throwing the event.
=> Throw overspeed event immediately, accounting for minimumDuration

src/main/java/org/traccar/protocol/RuptelaProtocolDecoder.java
Hi,
this pull request fixes a bug (first reported to me by Joao Santos via email, thanks!) where Ruptela Extended Messages could split the records to merge in two messages. Eg: the device buffered a lot of extended records (more than 11 that go into one message) because of network problems or some such, and then when it started sending them it could happen that first message contained some records that should be merged with the records in second message. When that second message came, the system previously errored out because it couldn't merge them, as the array of records (= positions in Traccar) was empty. So the correct solution is/was to get the last stored record/position and merge it with that one. 
I was finally able to replicate this and figure it out. I'm also preparing some more …
=> Ruptela - Heartbeat support & extended records spanning multiple messages fix

src/main/java/org/traccar/protocol/T800xProtocolDecoder.java
The devices that use header `0x2323` can't establish a stable TCP connection which can lead to unexpected behavior because the devices don't receive the correct response from the server for login/heartbeat messages.
According to the attached document, the devices of header `0x2323` are expecting the response to have the serial bytes to be `0x00 0x01` in response messages.
steps:
1. the device sends a login message to the server ex. `232301001500030[IMEI]150208625020`
2. the server responds with `232301000f00010[IMEI]` which is the same message that the device sent. note that the serial bytes are `0x00 0x01`
3. the device sends a heartbeat message to the server ex. `232303000f00b50[IMEI]`
4. the server responds with `232303000f00010[IMEI]` which is the same message that the device sent. …
=> (Bugfix-T800X Protocol) Fix messages response for 0x2323

src/main/java/org/traccar/handler/ComputedAttributesHandler.java
Following #5036, this PR adds the Date class to the JEXL sandbox whitelist.
=> Allow Date class in the JEXL Sandbox.

src/main/java/org/traccar/protocol/Tlt2hProtocolDecoder.java
This contribution introduces the `SHAKE` event. It has been verified with the Mictrack MT700. MT700 emits this event when configured in Mode 4, 7 or 0. It is the first event sent after wake-up due to a detected vibration.
=> tlt2h protocol: Add `SHAKE` event

src/main/java/org/traccar/protocol/Tlt2hProtocol.java
This contribution aims to enable UDP support for the tlt2h protocol. I have a Mictrack MT700 at hand and verified the UDP mode working with this change successfully. The datagrams sent turned out to be identical to those sent in TCP mode.
However, I'm not too familiar with the code base so I don't know if that is enough.
Closes https://github.com/traccar/traccar/issues/5307
=> tlt2h protocol: Enable UDP

src/main/java/org/traccar/protocol/Tlt2hProtocolDecoder.java
Currently, the tlt2h decoder used with UDP does not correctly detect the end of the datagram, leading to a second empty position returned in [positions](https://github.com/frederictobiasc/traccar/blob/da82ef8979c23496bbf3507f34fc410e5f86f8ed/src/main/java/org/traccar/protocol/Tlt2hProtocolDecoder.java#L249) (see example contents of `positions` below.  This results for instance in networks, battery voltage, ... being never shown in the `details` view of a device. This was initially reported in https://github.com/traccar/traccar/pull/5344#issuecomment-2266344264.
I confirm that this fixes the issue.
Is it fine to fix this by introducing the CharacterDelimiterFrameDecoder also used by the TCP handler, or should we rather catch this in the frame decoder itself?
Contents of …
=> tlt2h: Fix handling UDP

src/main/java/org/traccar/api/resource/NotificationResource.java
Managers should also be allowed to send announcements, since they can have many users bellow them to manage.
Plus, this would enhance the announcements feature to cover scenarios of Traccar servers where managers want to send information to their managed users.
=> Allow managers to send announcements

src/main/java/org/traccar/web/WebServer.java
Hi,
while combing thorough warnings, I found a low hanging fruit:
> WARN: JAXBContext implementation could not be found. WADL feature is disabled.
As WADL is not used anywhere and disabling it is one line config change, I implemented it for cleaner logs.
=> Disable unused Jersey WADL

src/main/java/org/traccar/protocol/TrvProtocolDecoder.java
[Gps Watch protocol_2023.pdf](https://github.com/user-attachments/files/17203195/Gps.Watch.protocol_2023.pdf)
No response for following IWAP Commands:
AP33
AP34
AP84
AP85
Attached is the protocol where the changes are visible. On page 20, you can see AP33; on page 21, AP34; and on page 23, AP84/AP85.
=> No response for some more IWAP Commands

src/main/java/org/traccar/config/Keys.java, src/main/java/org/traccar/web/WebServer.java
The session cookie does not have the HttpOnly attribute. This parameter tells the browser that the cookie can only be accessed by the server and not by client-side scripts.
See: [OWASP Testing for Cookies Attributes](https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/06-Session_Management_Testing/02-Testing_for_Cookies_Attributes)
This pull request adds a parameter to set the HttpOnly attribute to the session cookie. Personally, I would set this attribute to “true” by default, but I don't know the system-wide implications.
=> Security: Session cookie is not HttpOnly

src/main/java/org/traccar/MainModule.java, src/main/java/org/traccar/forward/PositionForwarderWialon.java
If data is bigger then MTU, UDP won't allow to send this. I try to change UDP to TCP, chunk data, but compression do it's best.
Compression is described at the end of this docs: https://extapi.wialon.com/hw/cfg/Wialon%20IPS_en_v_2_0.pdf
Tested on Wialon and build looks fine.
=> Add data compression to PositionForwarderWialon

src/main/java/org/traccar/api/AsyncSocketServlet.java, src/main/java/org/traccar/api/MediaFilter.java, src/main/java/org/traccar/api/resource/SessionResource.java, src/main/java/org/traccar/api/resource/UserResource.java, src/main/java/org/traccar/api/security/SecurityRequestFilter.java, src/main/java/org/traccar/database/OpenIdProvider.java, src/main/java/org/traccar/helper/SessionHelper.java, src/main/java/org/traccar/web/WebRequestLog.java
Session fixation is made possible by the unsafe practice of keeping the same value in session cookies before and after authentication.
In the generic exploitation of session-fixing vulnerabilities, an attacker can obtain a set of session cookies from the target website without first authenticating. He can then force these cookies into the victim's browser using various techniques. If the victim subsequently authenticates on the target website and the cookies are not updated at login, the victim will be identified by the session cookies chosen by the chosen by the attacker. The attacker is then able to impersonate the victim using these known cookies.
See: [OWASP Session Fixation](https://owasp.org/www-community/attacks/Session_fixation )
This pull request refresh the session cookie after …
=> Security: Session fixation

src/main/java/org/traccar/web/OverrideFilter.java
The server title in the Traccar web interface was displaying as garbled characters when set to Chinese strings due to a missing charset=utf-8 in the response Content-Type header. This change ensures that the server title is rendered correctly by explicitly setting the response's character encoding to UTF-8.
Changes:
- Modified the OverrideFilter class to set response.setCharacterEncoding("UTF-8").
- Ensured proper rendering of the title/description in the web interface.
Closes #5465
=> Fix: Set UTF-8 Encoding for Proper Rendering of Chinese Characters in Server Title

openapi.yaml
This resolves the issue described in the linked forum thread:
[Link to Traccar Forum topic](https://www.traccar.org/forums/topic/traccar-openapi-client-getusers-expirationtime-can-be-null-but-is-not-marked-as-nullable/
)
Tested and confirmed.
=> OpenAPI yaml: User expirationTime nullable: true

src/main/java/org/traccar/protocol/TeltonikaProtocolDecoder.java
Teltonika Devices can be configured to create a Geofence when the ignition is off.
If the device is moved out of the geofence with the ignition off, it creates an alarm.
=> Teltonika add Auto Geofence Alarm

openapi.yaml, src/main/java/org/traccar/api/resource/PositionResource.java
I found https://github.com/traccar/traccar/issues/4387 and the coresponding PR for its implementation https://github.com/traccar/traccar/pull/5061 which I based this on.
I already have some ids from the `/api/positions` endpoint which I want to easliy remove without constructing deviceId/from/to parameters.
I hope that request makes sense and the implementation isn't _too_ bad, I'm not often doing Java stuff. Thanks for maintaining this cool project (:
=> Add api endpoint to delete a singular position

build.gradle
- avoid using the aggregated `netty-all` artifact
- define `nettyVersion` variable and reference each required Netty module
- `./gradlew --version` *(fails: No route to host)*
=> Replace netty-all with modular dependencies

src/main/java/org/traccar/protocol/H02ProtocolDecoder.java
Based on the analysis of servers from pro.sinotrack.com and their responses, we added the same response that is required for binary queries. In the end, the solution works for Sinotrack ST-901L and no more repeating old queries accumulate.
I am attaching screenshots of requests and responses to my Traccar server for processing 2 different types of requests from Sinotrack ST-901L:
Related old pull request https://github.com/traccar/traccar/pull/5596
=> Add ACK response for Sinotrack ST-901L binary packets [protocol H02]

.github/workflows/release.yml, docker/Dockerfile.alpine, docker/Dockerfile.debian, docker/Dockerfile.ubuntu
@tananaev,
I have migrated and refactored the build and publication of Docker traccar/tracker images from the [traccar/traccar-docker repository](https://github.com/traccar/traccar-docker). Along with the creation of the new release, Docker images will be published on the Docker Hub and GitHub Container Registry.
To parallelize the publication, I split the submission into S3 and the Docker build. In the future can add another task to create a release on GitHub.
Before the first launch, you need to add the secrets `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`.
=> Add release delivery to Docker Hub and GHCR

docker/Dockerfile.alpine, docker/Dockerfile.debian, docker/Dockerfile.ubuntu
@magna-z what do you think about doing images like this?
Basically 3 stages:
1. Unzip Traccar package. Separate stage means that we can reuse this code between all images and don't need to worry about installing and cleaning up unzip.
2. Package minimal version of JRE. This is what we do for official installers. Makes sense to do it for docker as well. It can save us quite a bit in size. It's also reusable. The only difference is that alpine needs a different base package.
3. Final docker image. It's basically the same across all with different base.
In my local testing it saved about 100MB on alpine image size.
=> Optimize Docker images

docker/compose/traccar-mysql.yaml, docker/compose/traccar-timescaledb.yaml
In reference to #5615 and commit e5c8a22, the `wget` command in the Docker healthcheck used an invalid `-s` option (not supported in BusyBox wget). This caused the healthcheck to fail silently.
This update:
- Replaces `-s` with the correct `-S` to show server response
- Adds `--spider` to prevent wget from attempting to download and save the /api/health response as a file named `health,` which can lead to file conflicts and failing healthchecks
=> Fix for failing docker compose healthchecks failing

src/main/java/org/traccar/protocol/H02ProtocolDecoder.java, src/test/java/org/traccar/protocol/H02ProtocolDecoderTest.java
This PR should add support for the ST906 battery reporting provided as reply to CXZT command:
```
2025-08-09 21:19:15  INFO: [T13cb679d: h02 > 1.2.3.4] CXZT
2025-08-09 21:19:15  INFO: [T13cb679d: h02 < 1.2.3.4] *HQ,11223344,SMS,ST906(70SACD)_TQ_V_2.0 2024/06/07\nID:11223344\nIP:1.2.3.4 5013\nUT:30,30,300\nVOLT:13.1V\nAPN:internet.example.com\nGPS:A-22-20\nGSM:26#
```
My plan is to run CXZT command using API every hour and use computed attributes to have it in the logs and screen.
=> Add support to decode car acc status for h02 protocol

templates/notifications/pt_BR/alarm.vm, templates/notifications/pt_BR/commandResult.vm, templates/notifications/pt_BR/deviceExpiration.vm, templates/notifications/pt_BR/deviceExpirationReminder.vm, templates/notifications/pt_BR/deviceFuelDrop.vm, templates/notifications/pt_BR/deviceFuelIncrease.vm, templates/notifications/pt_BR/deviceInactive.vm, templates/notifications/pt_BR/deviceMoving.vm, templates/notifications/pt_BR/deviceOffline.vm, templates/notifications/pt_BR/deviceOnline.vm, templates/notifications/pt_BR/deviceOverspeed.vm, templates/notifications/pt_BR/deviceStopped.vm, templates/notifications/pt_BR/deviceUnknown.vm, templates/notifications/pt_BR/driverChanged.vm, templates/notifications/pt_BR/geofenceEnter.vm, templates/notifications/pt_BR/geofenceExit.vm, templates/notifications/pt_BR/ignitionOff.vm, templates/notifications/pt_BR/ignitionOn.vm, templates/notifications/pt_BR/maintenance.vm, templates/notifications/pt_BR/media.vm, templates/notifications/pt_BR/passwordReset.vm, templates/notifications/pt_BR/queuedCommandSent.vm, templates/notifications/pt_BR/userExpiration.vm, templates/notifications/pt_BR/userExpirationReminder.vm
Add Brazilian Portuguese (pt_BR) notification templates under templates/notifications/pt_BR/.
This follows the new i18n folder layout and enables localized notifications when the user/server language is set to pt_BR.
Motivation
Provide first-class localization for Portuguese (Brazil) users.
Align custom templates with the new templates/notifications/<lang>/ structure introduced in recent releases.
Keep subject/digest + HTML bodies consistent across events.
What’s included
New folder: templates/notifications/pt_BR/
Initial set of templates (this PR):
queuedCommandSent.vm, userExpiration.vm, userExpirationReminder.vm
(More events can be added in follow-ups as needed.)
Template details
Each template sets:
#set($subject = "...")
#set($digest = "...")
HTML body includes:
Device and timestamp …
=> Add pt_BR Language on Template Folder

src/main/java/org/traccar/helper/PositionLogger.java, src/main/java/org/traccar/protocol/T55ProtocolDecoder.java, src/test/java/org/traccar/protocol/T55ProtocolDecoderTest.java
Updated NMEA (T55) protocol:
- Added the altitude and number of sats to GGA message
- Added GLL message parser
Updated PositionLogger to be able to show the altitude if it is configured in `logger.attributes`.
But the speed, course, altitude any many other parameters in the `Position` structure are not optional and may contain invalid values. For example Ebyte E108-GN03G reports the following
```
$GNGGA,193526.000,5332.16315,N,04921.33849,E,1,15,1.5,141.0,M,0.6,M,,*76\r\n
$GNGLL,5332.16315,N,04921.33849,E,193526.000,A,A*41\r\n
$GNGSA,A,3,03,06,12,24,25,32,195,,,,,,2.7,1.5,2.2,1*0B\r\n
$GNGSA,A,3,14,27,40,42,45,,,,,,,,2.7,1.5,2.2,4*36\r\n
$GNGSA,A,3,76,75,67,,,,,,,,,,2.7,1.5,2.2,2*31\r\n
$GPGSV,3,1,11,03,12,034,37,06,50,110,13,11,31,159,,12,57,286,38,0*6C\r\n …
```
=> Updated NMEA protocol
