traccar/traccar

src/org/traccar/protocol/OsmAndProtocolDecoder.java
Added a new param for getting a text description. Holds additional information about the position, for saving manual POIs.
=> Add new param to OsmAnd protocol

debug.xml, src/org/traccar/AlertHandler.java, src/org/traccar/BasePipelineFactory.java, src/org/traccar/database/DataManager.java, src/org/traccar/model/Alert.java
got this warning if it has double quotes
======
2015-06-10 17:41:00  WARN: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"SELECT userId, deviceId FROM user_device;"' at line 1 - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException (NativeConstructorAccessorImpl.java:-2)
=> removing double quotes

src/org/traccar/Context.java, src/org/traccar/geocode/OpenCageReverseGeocoder.java
Reverse geocoder for OpenCage
http://geocoder.opencagedata.com/
=> Add OpenCage ReverseGeodecoder

src/org/traccar/Context.java, src/org/traccar/geocode/BingMapsReverseGeocoder.java, src/org/traccar/geocode/FactualReverseGeocoder.java
BingMaps ReverseGeocoder
https://msdn.microsoft.com/en-us/library/ff701710.aspx
=> Add BingMaps ReverseGeocoder

debug.xml, setup/unix/traccar.xml, setup/windows/traccar.xml, src/org/traccar/model/Event.java, src/org/traccar/protocol/BlackKiteProtocol.java, src/org/traccar/protocol/BlackKiteProtocolDecoder.java, test/org/traccar/protocol/BlackKiteProtocolDecoderTest.java, tools/opengts.xml
BlackKite is closely based on the Galileo protocol. We derive code
from the Galileo protocol and make changes as required to meet
BlackKite protocol specifications.
=> Add support for BlackKite protocol.

src/org/traccar/web/WebServer.java
According to the jackson doc: https://jersey.java.net/documentation/latest/user-guide.html#json.jackson
I added one line to the code and resolved the problem.
=> Fix new api java<->json conversion problem #1859

src/org/traccar/protocol/H02Protocol.java, src/org/traccar/protocol/H02ProtocolEncoder.java
Supported commands update + checkstyle fix.
=> H02 supported commands update

src/org/traccar/BaseProtocol.java, web/app/view/CommandDialog.js, web/app/view/CommandDialogController.js, web/l10n/en.json, web/l10n/ru.json
1. Added TYPE_CUSTOM to list of supported commands for all protocols
2. Extended Web UI
=> Custom command support for web interface

database/changelog-3.6.xml, database/changelog-master.xml, setup/unix/traccar.xml, setup/windows/traccar.xml, src/org/traccar/BaseEventHandler.java, src/org/traccar/BasePipelineFactory.java, src/org/traccar/api/AsyncSocket.java, src/org/traccar/api/resource/EventResource.java, src/org/traccar/database/ConnectionManager.java, src/org/traccar/database/DataManager.java, src/org/traccar/events/CommandResultEventHandler.java, src/org/traccar/events/MotionEventHandler.java, src/org/traccar/events/OverspeedEventHandler.java, src/org/traccar/model/Device.java, src/org/traccar/model/Event.java, src/org/traccar/web/WebServer.java
What have done:
A model and a database store (+ added liquibase changelog)
A base class for events handlers
Three example handlers in a separate package org.traccar.events
`CommandResultEventHandler` - just fire an event if there is "result" in position attributes
`OverspeedEventHandler` - fire an event if the device exceeds the speed (has draft for by group and by device speedlimiting, needs model and UI extension)
`MotionEventHandler` - fire an event on device motion, used new device field and extended updateDeviceStatus
Last two can suppres repeated events.
`ConnectionManager` fire events on offline/online, sends new events in websocket.
API represents events by ID and last events for period (in seconds).
In the last commit I've added synchronization `devicesById` and database, I think …
=> Events subsystem

debug.xml, setup/unix/traccar.xml, setup/windows/traccar.xml, src/org/traccar/protocol/LdplProtocol.java, src/org/traccar/protocol/LdplProtocolDecoder.java, test/org/traccar/protocol/LdplProtocolDecoderTest.java
[all_ascii.txt](https://github.com/tananaev/traccar/files/305970/all_ascii.txt)
There is some unused group values. Do you wanna remove the group ?
=> Ldpl protocol - review

web/app/view/AttributeDialog.js, web/app/view/Attributes.js, web/app/view/AttributesController.js, web/app/view/UserDialog.js, web/app/view/UserDialogController.js, web/l10n/en.json
It can be easily reused, just pass `attributes` to view
=> Added attributes editor

src/org/traccar/geofence/GeofencePolygon.java, test/org/traccar/geofence/GeofencePolygonTest.java
Subj for compatibility with `ol.format.WKT ()`
=> Double brackets for "POLYGON" area

web/app/view/GeofenceDialogController.js, web/app/view/GeofenceMap.js
There is nice feature, polygon can be edited without drawing new but circle should be redrawn.
=> Load area for editing geofence.

src/org/traccar/protocol/AstraProtocol.java
As described on received manual, the protocol is the same for TCP and UDP.
=> UDP support for Astra K protocol

src/org/traccar/model/Command.java, src/org/traccar/protocol/Pt502Protocol.java, src/org/traccar/protocol/Pt502ProtocolEncoder.java, test/org/traccar/protocol/Pt502ProtocolEncoderTest.java
- Fixed output control format.
- Added command for set maxSpeed and sms timezone.
=> Pt502 command fix

src/org/traccar/protocol/GranitProtocolDecoder.java
Shame on me, missed typo.
Sorry for so much corrections
=> Fix typo in GranitProtocolDecoder

web/app/view/Notifications.js
=> Remove red mark from grid

debug.xml, setup/unix/traccar.xml, setup/windows/traccar.xml
=> Fix user attributes saving

web/app/view/AttributesController.js, web/app/view/Notifications.js
Here is style fixes founded by `jscs` as promised.
=> Style fixes in JS code

src/org/traccar/protocol/SuntechProtocolEncoder.java
This is my last mistake, I dont know how it passed my site check.
After you accept this pull request I will submit a new travis build script that will run checkstyle after testes, preventing any future errors on every pull request from others developers.
=> Fixed tags

debug.xml, schema/changelog-3.7.xml, setup/unix/traccar.xml, setup/windows/traccar.xml, src/org/traccar/database/DeviceManager.java, src/org/traccar/model/Device.java, web/app/model/Device.js, web/app/view/AttributesController.js, web/app/view/DeviceDialog.js, web/app/view/DeviceDialogController.js
Hello, lets continue.
Added attributes to Device model, actually without payload, but I'm planning to use it at least to store device pin-code to send commands.
Also:
- Fixed license header for `DeviceManager.java`
- Fixed editing attributes for not saved (new) object (`AttributesController.js`)
PS: I've noticed some repeated code in controllers, it is need to be optimized with inheritance.
=> Attributes for devices

src/org/traccar/database/GeofenceManager.java
This should fix some deadlocks
=> Split locks in GeofenceManager.refresh() and try to avoid crosslocks with devices.

src/org/traccar/protocol/EasyTrackProtocolDecoder.java
=> Correctly process negative latitude and longitude.

debug.xml, schema/changelog-3.7.xml, setup/unix/traccar.xml, setup/windows/traccar.xml, src/org/traccar/DefaultDataHandler.java, src/org/traccar/MainEventHandler.java, src/org/traccar/database/DeviceManager.java, src/org/traccar/events/GeofenceEventHandler.java, src/org/traccar/events/MotionEventHandler.java, src/org/traccar/events/OverspeedEventHandler.java, src/org/traccar/model/Device.java
- Optimize MotionEventHandler to do not use Device.motion
- Remove Device.motion from model and database
- some optimizations
=> Move lastPosition update to the end of pipeline

src/org/traccar/model/Position.java, src/org/traccar/protocol/AutoFonProtocolDecoder.java, src/org/traccar/protocol/Avl301ProtocolDecoder.java, src/org/traccar/protocol/BlackKiteProtocolDecoder.java, src/org/traccar/protocol/CarTrackProtocolDecoder.java, src/org/traccar/protocol/CarcellProtocolDecoder.java, src/org/traccar/protocol/Gps103ProtocolDecoder.java, src/org/traccar/protocol/GranitProtocolDecoder.java, src/org/traccar/protocol/Gt06ProtocolDecoder.java, src/org/traccar/protocol/H02ProtocolDecoder.java, src/org/traccar/protocol/Jt600ProtocolDecoder.java, src/org/traccar/protocol/MeiligaoProtocolDecoder.java, src/org/traccar/protocol/MxtProtocolDecoder.java, src/org/traccar/protocol/NavisProtocolDecoder.java, src/org/traccar/protocol/NoranProtocolDecoder.java, src/org/traccar/protocol/ProgressProtocolDecoder.java, src/org/traccar/protocol/SuntechProtocolDecoder.java, src/org/traccar/protocol/Tk103ProtocolDecoder.java, src/org/traccar/protocol/TotemProtocolDecoder.java, src/org/traccar/protocol/UlbotechProtocolDecoder.java
I know it is not good to do not finished pull request, but it is a huge work to analyze documentation and decode alarms. Frankly, I want to avoid redoing it if I made a mistake in the beginning.
Please take a look if I do it in a right way of course if you have a time. If there is a principle problem let me know.
I decided to not combine different alarms and did like you in `MiniFinder`
It is not finished yet. I'll add other protocols gradually in this pull request.
=> Organized alarms in the first part of protocols

debug.xml, src/org/traccar/BasePipelineFactory.java, src/org/traccar/database/IdentityManager.java, src/org/traccar/events/IgnitionEventHandler.java, src/org/traccar/events/MotionEventHandler.java, src/org/traccar/events/OverspeedEventHandler.java, src/org/traccar/model/Event.java, src/org/traccar/notification/NotificationFormatter.java, src/org/traccar/protocol/IdplProtocolDecoder.java, src/org/traccar/protocol/Stl060ProtocolDecoder.java, src/org/traccar/protocol/VisiontekProtocolDecoder.java, src/org/traccar/reports/Events.java, src/org/traccar/reports/ReportUtils.java, src/org/traccar/reports/Route.java, src/org/traccar/reports/Summary.java, src/org/traccar/reports/model/SummaryReport.java, test/org/traccar/EventHandlerTest.java, test/org/traccar/ProtocolTest.java, test/org/traccar/events/AlertEventHandlerTest.java, test/org/traccar/events/CommandResultEventHandlerTest.java, test/org/traccar/events/IgnitionEventHandlerTest.java, test/org/traccar/events/MotionEventHandlerTest.java, tools/test-generator.py, web/app/AttributeFormatter.js, web/app/model/ReportSummary.js, web/app/view/ReportController.js, web/l10n/en.json
I just wanted to do small pull request, but...
- Added `IgnitionEventHandler`
- Added Motor Hours to Summary report
Also
- Added Unit tests for some event handlers
- Added message template for alarms
- If you don't mind, I've added `ignition` to `test-generator.py`
=> Ignition and Motor Hours

src/org/traccar/BasePipelineFactory.java, src/org/traccar/DistanceHandler.java, src/org/traccar/model/Position.java, src/org/traccar/reports/Summary.java, test/org/traccar/DistanceHandlerTest.java, web/app/AttributeFormatter.js
It is small this time
- `DistanceHandler` is always enabled now
- Summary distance is calculated by "odometer" if exist or by "distance" if not
=> Changed way of summary distance calculation

src/org/traccar/Config.java, src/org/traccar/events/MotionEventHandler.java
fix #2214 
- Made speed threshold configurable
- Added `Config.getDouble()`
=> Made speed threshold configurable

src/org/traccar/protocol/EelinkProtocolDecoder.java, src/org/traccar/protocol/Gt06ProtocolDecoder.java, src/org/traccar/protocol/HuabaoProtocolDecoder.java, src/org/traccar/protocol/IdplProtocolDecoder.java, src/org/traccar/protocol/MegastekProtocolDecoder.java, src/org/traccar/protocol/TzoneProtocolDecoder.java, test/org/traccar/protocol/Gt06ProtocolDecoderTest.java
Added alarm decoding for 5 protocols that have documentation.
Not sure about Megastek, but according my intuition should work for all patterns.
I think we can change it in future if something wrong according to users feedback.
=> Alarm decoding for next protocols

src/org/traccar/protocol/Gt06ProtocolDecoder.java, src/org/traccar/protocol/KenjiProtocolDecoder.java, src/org/traccar/protocol/T800xProtocolDecoder.java, src/org/traccar/protocol/TytanProtocolDecoder.java, src/org/traccar/protocol/XexunProtocolDecoder.java
Fixed alarm decoding for more protocols 
There is no list of possible alarms in Xexun, in the tests only "help me!", I've added some from SMS answers that can be.
=> Alarm decoding for few more protocols

src/org/traccar/api/resource/ReportResource.java, src/org/traccar/reports/ReportUtils.java, src/org/traccar/reports/Summary.java, src/org/traccar/reports/Trips.java, src/org/traccar/reports/model/BaseReport.java, src/org/traccar/reports/model/SummaryReport.java, src/org/traccar/reports/model/TripReport.java, test/org/traccar/reports/ReportUtilsTest.java, tools/test-generator.py, web/app/Application.js, web/app/AttributeFormatter.js, web/app/model/ReportTrip.js, web/app/store/ReportSummary.js, web/app/store/ReportTrips.js, web/app/view/ReportController.js, web/l10n/en.json
- Added trips report, key features of trips detector are here #2224
- Refactored reports models and moved some code to `ReportUtils`
- Added tests for `ReportUtils`
I've added "Spent fuel" only to trips (not summary) because it is very unlikely that fuel increases during a trip. It is calculated only for 3 protocols for now. It is String and formatted in java, because web-client never knows which format is used for `KEY_FUEL`.
If you don't mind I've added `speed` to `test-generator.py`. It helps to test motion, overspeed, and trips detector.
Also I can add comments to `detectTrips` for how it is work explanation if need.
=> Trips reports

src/org/traccar/model/Position.java, src/org/traccar/protocol/AtrackProtocolDecoder.java, src/org/traccar/protocol/BoxProtocolDecoder.java, src/org/traccar/protocol/DishaProtocolDecoder.java, src/org/traccar/protocol/EasyTrackProtocolDecoder.java, src/org/traccar/protocol/Gl200ProtocolDecoder.java, src/org/traccar/protocol/IntellitracProtocolDecoder.java, src/org/traccar/protocol/Jt600ProtocolDecoder.java, src/org/traccar/protocol/MegastekProtocolDecoder.java, src/org/traccar/protocol/Mta6ProtocolDecoder.java, src/org/traccar/protocol/NavisProtocolDecoder.java, src/org/traccar/protocol/Pt502ProtocolDecoder.java, src/org/traccar/protocol/RitiProtocolDecoder.java, src/org/traccar/protocol/TotemProtocolDecoder.java, src/org/traccar/protocol/TytanProtocolDecoder.java, src/org/traccar/protocol/WondexProtocolDecoder.java, src/org/traccar/protocol/XirgoProtocolDecoder.java, src/org/traccar/reports/ReportUtils.java, test/org/traccar/reports/ReportUtilsTest.java
- Made changes to use meters in `KEY_ODOMETER`
- Other changes to use right keys in some protocols
=> Odometer units for first part of protocols

setup/unix/traccar.xml, setup/windows/traccar.xml
Debug.xml has more ports than others XML files.
=> Added missing ports declaration.

src/org/traccar/api/resource/DevicePermissionResource.java, src/org/traccar/api/resource/DeviceResource.java, src/org/traccar/api/resource/GroupPermissionResource.java, src/org/traccar/api/resource/GroupResource.java, src/org/traccar/api/resource/SessionResource.java, src/org/traccar/api/resource/UserResource.java, src/org/traccar/database/PermissionsManager.java, src/org/traccar/notification/NotificationMail.java, web/app/view/DevicesController.js, web/app/view/SettingsMenu.js, web/app/view/SettingsMenuController.js
- Implemented users cache
Also while testing I've noticed that some buttons and menu items is not hidden from readonly user, fixed it.
The only button for devices is "Send command". It is not forbidden in API. 
Is it OK that readonly user can send commands?
=> Users cache

src/org/traccar/helper/UnitsConverter.java, src/org/traccar/notification/NotificationFormatter.java
- Added speed converting in NotificationFormatter
- Used constants in UnitsConverter
Partially fix https://www.traccar.org/forums/topic/setting-the-speed-limit-and-speed-limit-notifications/
Sorry for duplicate.
=> Convert speed units in mail notifications v2

src/org/traccar/protocol/AstraProtocolDecoder.java, src/org/traccar/protocol/GoSafeProtocolDecoder.java, src/org/traccar/protocol/HuaShengProtocolDecoder.java, src/org/traccar/protocol/MtxProtocolDecoder.java, src/org/traccar/protocol/TaipProtocolDecoder.java, src/org/traccar/protocol/VisiontekProtocolDecoder.java
=> A few more odometer units

src/org/traccar/reports/Trips.java
More explanation in #2251 
`report.trip.greedyParking = true` means algorithm tends to be in "parking state". Only continuous trips longer than minimal detected.
Default `report.trip.greedyParking = false` means algorithm tends to be in "trip state". Only continuous parking longer than minimal can divide trip.
=> Made trips detector behavior configurable

src/org/traccar/protocol/TelicProtocolDecoder.java
Fix #2256 
Here is also km/h https://github.com/tananaev/traccar/issues/691
=> Fix telic protocol speed units

src/org/traccar/protocol/WialonProtocolDecoder.java
Why 218 km/h top speed did not confuse me earlier...
Same problem, it is km/h according to documentation.
=> Fix wialon protocol speed units

swagger.json
Added only json because of https://github.com/OAI/OpenAPI-Specification/issues/146
=> Actualize swagger.json with reports

web/app/view/CommandDialog.js, web/app/view/CommandDialogController.js, web/l10n/en.json
In addition to https://github.com/tananaev/traccar/commit/ae5fe50416df190f5374d084526518a22096871e
=> Rename phoneNumber constant and field in web

web/app/controller/Root.js, web/app/view/BasePermissionsController.js, web/app/view/DevicesController.js, web/app/view/GroupsController.js, web/app/view/NotificationsController.js, web/app/view/UsersController.js
`find` by default uses RegExp
Should fix  #2278
=> Fix find index in BasePermissionsController.js

src/org/traccar/events/OverspeedEventHandler.java
=> Use knots for speedLimit

src/org/traccar/protocol/WatchProtocolDecoder.java, test/org/traccar/protocol/WatchProtocolDecoderTest.java
=> Watch: Handle answer on pulse command

web/app/view/ReportController.js
=> Move column sets outside the method

src/org/traccar/database/DeviceManager.java, src/org/traccar/events/OverspeedEventHandler.java, src/org/traccar/reports/ReportUtils.java, src/org/traccar/reports/Summary.java, src/org/traccar/reports/Trips.java, src/org/traccar/web/CsvBuilder.java
Added this parameter to flexibly configure distance calculation.
In continue https://www.traccar.org/forums/topic/%D0%BD%D0%B5-%D1%80%D0%B0%D1%81%D1%81%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D0%B5%D1%82-%D0%BF%D1%80%D0%BE%D0%B9%D0%B4%D0%B5%D0%BD%D0%BE%D0%B5-%D1%80%D0%B0%D1%81%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8-2/
=> Add parameter "report.ignoreOdometer"

src/org/traccar/api/resource/AttributeAliasResource.java
As discussed here https://github.com/tananaev/traccar-web/pull/287#discussion_r80353811
=> Change aliases API path

debug.xml, src/org/traccar/database/ConnectionManager.java
Made status events "disablable" in continue to https://www.traccar.org/forums/topic/event-onlineoffline/
=> Make status events switchable

src/org/traccar/notification/EventForwarder.java
=> Changed Content-Type for easy access to data from PHP and others

src/org/traccar/protocol/Gl200ProtocolDecoder.java, test/org/traccar/protocol/Gl200ProtocolDecoderTest.java
=> GL200: Handle ACK packets as command result

src/org/traccar/protocol/Gl200ProtocolDecoder.java, test/org/traccar/protocol/Gl200ProtocolDecoderTest.java
=> GL200: Handle SOS button

debug.xml, src/org/traccar/protocol/TkmateProtocol.java, src/org/traccar/protocol/TkmateProtocolDecoder.java, test/org/traccar/protocol/TkmateProtocolDecoderTest.java
Please advice any changes needs to be done. Thanks.
.Attached protocol document.
[TMD-200 Protocol.pdf](https://github.com/tananaev/traccar/files/506307/TMD-200.Protocol.pdf)
=> Implement trakmate protocol

src/org/traccar/FilterHandler.java
This is useful to know which filters have been used to filter out data if you enabled multiple filters.
=> Log which filters have been used

debug.xml, schema/changelog-3.8.xml, src/org/traccar/model/Device.java
=> Extend device model with management info

src/org/traccar/api/resource/PositionResource.java, src/org/traccar/helper/UnitsConverter.java, src/org/traccar/web/CsvBuilder.java, src/org/traccar/web/GpxBuilder.java
Export only base values supported by GPX schema
- `latitude`
- `longitude`
- `fixTime` as `time`
- `altitude` as `geoidheight` (had some doubds, but think it fits better than `elevation`)
- `course`
- `speed`
=> Export positions to GPX

swagger.json
Looks like forget nothing since 3.7 release
=> Update swagger.json with recent changes

src/org/traccar/model/Position.java, src/org/traccar/protocol/Gps103ProtocolDecoder.java
My first try code modification to add gps103 events
=> Add acc on, acc off and door alarm to events from coban gps 

schema/changelog-3.8.xml, setup/default.xml, src/org/traccar/api/SecurityRequestFilter.java, src/org/traccar/api/resource/DeviceResource.java, src/org/traccar/api/resource/SessionResource.java, src/org/traccar/api/resource/UserResource.java, src/org/traccar/database/PermissionsManager.java, src/org/traccar/model/User.java
@Abyss777, can you please review the changes.
Added:
- Flag to disable users
- Expiration date
- Device limit for user
Now to change any admin-related values user should be admin. It's easier logic, but it means that user won't be able to make itself readonly like before. Probably a good thing :)
I have hidden some field in the web UI for non-admins. Otherwise too many parameters.
=> Add user expiration and device limit

src/org/traccar/BaseProtocol.java, src/org/traccar/BaseProtocolEncoder.java, src/org/traccar/DistanceHandler.java, src/org/traccar/FilterHandler.java, src/org/traccar/database/DeviceManager.java, src/org/traccar/events/IgnitionEventHandler.java, src/org/traccar/events/MaintenanceEventHandler.java, src/org/traccar/model/Extensible.java, src/org/traccar/notification/PropertiesProvider.java, src/org/traccar/protocol/CityeasyProtocolEncoder.java, src/org/traccar/protocol/EelinkProtocolEncoder.java, src/org/traccar/protocol/Gt06ProtocolEncoder.java, src/org/traccar/protocol/Jt600ProtocolEncoder.java, src/org/traccar/protocol/MeiligaoProtocolEncoder.java, src/org/traccar/protocol/NoranProtocolEncoder.java, src/org/traccar/protocol/RuptelaProtocolEncoder.java, src/org/traccar/protocol/T800xProtocolEncoder.java, src/org/traccar/protocol/TeltonikaProtocolEncoder.java, src/org/traccar/protocol/WatchProtocolEncoder.java, src/org/traccar/reports/ReportUtils.java, src/org/traccar/reports/Summary.java
Added helpers to `Extensible` class
Used them where needed.
Actually, `getLong` is never used, added just to consistence.
=> Attributes helpers

src/org/traccar/CopyAttributesHandler.java, src/org/traccar/database/DeviceManager.java, src/org/traccar/events/MaintenanceEventHandler.java, src/org/traccar/events/OverspeedEventHandler.java, src/org/traccar/reports/Summary.java, src/org/traccar/reports/Trips.java
=> Combine lookupAttribute helpers

src/org/traccar/protocol/Gps103Protocol.java
Fix this.
```
2016-11-08 16:08:09 DEBUG: [7809CEC1: 5001 < 186.167.248.13] HEX: 696d65693a3836383638333032353232303638362c767431352c2c2c4c2c2c2c326634342c2c386436312c2c2c2c2c302c302c302e3030252c2c3b696d65693a3836383638333032353232303638362c76722c30303030666130316666643866666462303038343030313430653066313230663064313431323130313231373135313431383165333232313165316331633165336432633265323433323439343034633462343734303436343535303561373336323530353536643536343534363634383836353664373737623831383238313465363038643937386337643936373337653831376330313135313731373165316131653362323132313362376335333436353337633763376337633763376337633763376337633763376337633763376337633763376337633763376337633763376337633763376337633763376337633763376337633763376337633763376337633763376337633763376337633763376337 …
```
=> Images from coban gps not exception.

README.md, setup/docker/Dockerfile, setup/docker/build.sh
Hi Anton,
I have fixed the stuff, I'm able to create an images and I can run the container.
I'm close, I see javascript spinning wheel trying to load login page
maybe you can inspect what I have done and to make it 100% working!
Thanks,
Bas
=> small fixes getting image build again

setup/default.xml, src/org/traccar/api/resource/PositionResource.java, src/org/traccar/database/DataManager.java
It is needed to show events on map
- Added request to get position by Id
- Added parameter to API
The only note is HTTP request length. It is depending on browser 300 - 1500 positions at once.
But GET is more natural for REST API.
=> Add API to get positions by Id

src/org/traccar/api/resource/NotificationResource.java, src/org/traccar/notification/NotificationMail.java
- added API point `api/users/notifications/testmail` that sends "unknown" event on GET request
- make `sendMailSync` public
- moved try/catch to runable
I decided to throw exceptions in resource. It will help debug without looking in log file.
=> Implement API to test mail

src/org/traccar/Context.java, src/org/traccar/notification/NotificationFormatter.java, templates/mail/alarm.vm, templates/mail/commandResult.vm, templates/mail/deviceMoving.vm, templates/mail/deviceOffline.vm, templates/mail/deviceOnline.vm, templates/mail/deviceOverspeed.vm, templates/mail/deviceStopped.vm, templates/mail/deviceUnknown.vm, templates/mail/geofenceEnter.vm, templates/mail/geofenceExit.vm, templates/mail/ignitionOff.vm, templates/mail/ignitionOn.vm, templates/mail/maintenance.vm
- Used velocity engine properties to pass `web.url` to formatter. Checked documentation, it does not intersect with velocity properties.
About templates...
I called line "Link:" if event does not have assigned position, and "Point:" if has.
=> Added links to server in mail templates

templates/mail/alarm.vm, templates/mail/deviceMoving.vm, templates/mail/deviceOverspeed.vm, templates/mail/deviceStopped.vm, templates/mail/geofenceEnter.vm, templates/mail/geofenceExit.vm, templates/mail/ignitionOff.vm, templates/mail/ignitionOn.vm, templates/mail/maintenance.vm
This causes display issues in some mail clients
=> Put the html code for degree instead of the special character

src/org/traccar/events/MaintenanceEventHandler.java, src/org/traccar/events/OverspeedEventHandler.java
fix #2701 
Should I declare "speed" constant somewhere?
=> Add attributes to overspeed and maintenance events

schema/changelog-3.10.xml, setup/default.xml, src/org/traccar/model/Calendar.java, test/org/traccar/calendar/CalendarTest.java, test/org/traccar/reports/TripsTest.java
Changes:
- Rename calendarData to data
- Use CalendarComponent only
- Use diamond operator in two places 
Also fixed TripsTest, I do not know why it was working for you, but I had the same issue as in #2750
=> Cleanup calendar model

src/org/traccar/notification/NotificationFormatter.java
=> Fix mail template encoding

templates/mail/test.vm
fix #2792 
I think test template is more natural than "unknown"
=> Add test mail template

src/org/traccar/protocol/TeltonikaProtocolDecoder.java
Branched decode() execution based on Channel implementation (decodeTCP/decodeUDP).
decodeTCP() has original decode() execution.
decodeUDP() consumes headers and retrieves IMEI then parses data.
parseData() has been adapted to reply to UDP accordingly.
And finally checked and adjusted code styles.
=> Added UDP support on Teltonika Decoder

src/org/traccar/events/IgnitionEventHandler.java, test/org/traccar/events/IgnitionEventHandlerTest.java
=> Rise ignition events only if both positions has ignition attribute

src/org/traccar/database/PermissionsManager.java
=> Clear deviceUsers cache before refresh

src/org/traccar/protocol/TelicProtocolDecoder.java
=> #2793 Added some Telic events (alarm)

schema/changelog-3.10.xml
Replaced `fk_user_user_manageduserid` in MS SQL with trigger (not sure in trigger name)
Also, you were right, we need drop `defaultValue` before add, because MS SQL do not have `SET DEFAULT` only `ADD DEFAULT`
fix #2884
=> Fix 3.10 schema for MS SQL

test/org/traccar/helper/ObdDecoderTest.java
Hello,
I open this pull request to specify the method [decodeCodes](https://github.com/tananaev/traccar/blob/master/src/org/traccar/helper/ObdDecoder.java#L59) of the `org.traccar.helper.ObdDecoder`
=> Improve test cases on ObdDecoder

swagger.json, tools/swagger2html.py
I have gone through the sources and made the updates as best as I could. Let me know if I've missed anything.
=> Update swagger with v3.10 changes

schema/changelog-3.11.xml, setup/default.xml, src/org/traccar/api/resource/CommandResource.java, src/org/traccar/database/PermissionsManager.java, src/org/traccar/model/Server.java
Also allowed "device readonly" users send commands
It is server part for this https://github.com/tananaev/traccar-web/issues/411
=> Server-wide "device readonly" flag

src/org/traccar/smpp/SmppClient.java
Schedule reconnection task only if previous finished
Fix infinite re-connection in some cases
=> Schedule smpp reconnection only if current task stopped

setup/default.xml
Looks like they were missed on some stage
=> Fix missed fields in updateServer request

src/org/traccar/notification/NotificationFormatter.java
Other classes can use the formatter, if this two methods are public.
=> make methods accessible to ther classes

src/org/traccar/protocol/MeitrackProtocolDecoder.java
In case of Meitrack devices to show the correct Battery and Power values some additional calculation required.
I had to recreate the whole request, github drived me crazy...
=> Show proper Battery and Power values - Update MeitrackProtocolDecoder.java

src/org/traccar/notification/NotificationMail.java
=> Add a Date: header in notification emails

src/org/traccar/protocol/Gt06Protocol.java, src/org/traccar/protocol/Gt06ProtocolEncoder.java
Hi Anton
Another small change for sending custom commands for GT06. I have made the change and test most of the commands and it is working fine.
Tested:
PARAM#, TIMER#, GPRSSET#, FENCE#, SOS#.
Could you please merge this also. It will be a great help.
Please let me know if any other changes are required for the same.
Thanks
=> Send any custom commands for GT06.

src/org/traccar/protocol/DishaProtocolDecoder.java, src/org/traccar/protocol/GlobalSatProtocolDecoder.java, src/org/traccar/protocol/Gt30ProtocolDecoder.java, src/org/traccar/protocol/MeiligaoProtocolDecoder.java, src/org/traccar/protocol/MeitrackProtocolDecoder.java, src/org/traccar/protocol/TotemProtocolDecoder.java, src/org/traccar/protocol/TrackboxProtocolDecoder.java, src/org/traccar/protocol/VisiontekProtocolDecoder.java, src/org/traccar/protocol/WialonProtocolDecoder.java, src/org/traccar/protocol/XirgoProtocolDecoder.java, test/org/traccar/ProtocolTest.java
Next portion ...
Organized `KEY_xDOP` values
=> Organize KEY_xDOP values

src/org/traccar/api/resource/AttributeResource.java
Did not create a new API point, just used POST with query parameter.
Pass `deviceId` as query param and try to apply `computedAttribute` to last position, if `deviceId` omitted will be default "add" behavior.
Check both, expression and type casting.
=> Implement testing API for computedAttribute

src/org/traccar/BasePipelineFactory.java, src/org/traccar/DistanceHandler.java, src/org/traccar/MotionHandler.java, src/org/traccar/events/MotionEventHandler.java, src/org/traccar/protocol/Gl200ProtocolDecoder.java, src/org/traccar/reports/ReportUtils.java, test/org/traccar/DistanceHandlerTest.java, test/org/traccar/MotionHandlerTest.java, test/org/traccar/ProtocolTest.java, test/org/traccar/events/MotionEventHandlerTest.java
Implemented motion handler in pipeline and use `Position_KEY_MOTION` for event generation and trips detection.
=> Centralized motion detection

src/org/traccar/protocol/GranitProtocolDecoder.java, src/org/traccar/protocol/WialonProtocolDecoder.java, src/org/traccar/protocol/WondexProtocolDecoder.java, test/org/traccar/ProtocolTest.java
- Test 'archive' attribute for boolean
- Add 'archive' attribute for wialon and granit
- Reverted check satellites in wondex
- Fixed typo in comment
=> Revert satellites check in wondex and add 'archive' in wialon and granit

src/org/traccar/protocol/SuntechProtocol.java, src/org/traccar/protocol/SuntechProtocolEncoder.java
I added the lines responsible for the commands on and off the alarm (output 2 of the Suntech tracker)
=> Command on and off alarm protocol Suntech

templates/sms/geofenceEnter.vm
This PR fixes a missing geofence name on enter for SMS.
=> SMS missing geofence name on enter

src/org/traccar/protocol/Tk103Protocol.java, src/org/traccar/protocol/Tk103ProtocolEncoder.java, test/org/traccar/protocol/Tk103ProtocolEncoderTest.java
Add  commands for Tk103 protocol:
* TYPE_POSITION_SINGLE,
* TYPE_POSITION_PERIODIC,
* TYPE_POSITION_STOP,
* TYPE_GET_VERSION,
* TYPE_REBOOT_DEVICE,
* TYPE_SET_ODOMETER
Actually I have a very limited device, so I could successfully test just the TYPE_POSITION_SINGLE command on the road.
=> Tk103 commands

src/org/traccar/smpp/EnquireLinkTask.java
We need schedule Reconnection Task here, not just only one attempt to reconnect
=> Fix SMPP reconnection on enquire link failed

src/org/traccar/api/resource/DeviceAttributeResource.java, src/org/traccar/api/resource/GroupAttributeResource.java
=> Fix Device and Group Computed Attribute unlinking

swagger.json
Actualized recent changes in API
=> Actualize swagger.json

src/org/traccar/Context.java, src/org/traccar/api/resource/SessionResource.java, src/org/traccar/api/resource/UserResource.java, src/org/traccar/database/DeviceManager.java, src/org/traccar/database/PermissionsManager.java, src/org/traccar/database/SimpleObjectManager.java, src/org/traccar/database/UsersManager.java
Next step
On the one hand it is an extra class, but on the other we are reusing code and unloading `PermissionsManager`
Also I hope we will optimize objects resources at least add/update/remove functions, separate managers should help for that.
=> Move users management to separate manager

setup/default.xml, src/org/traccar/database/DataManager.java
Added config parameter and enabled it in `default.xml`
=> Make query generator switchable

src/org/traccar/database/DataManager.java, test/org/traccar/database/DataManagerTest.java
Write both standard and extended fields on insert action
fix #3411
=> Write all fields on insert action

src/org/traccar/database/ConnectionManager.java, src/org/traccar/database/DeviceManager.java, src/org/traccar/events/MotionEventHandler.java, src/org/traccar/model/DeviceState.java, src/org/traccar/reports/ReportUtils.java, test/org/traccar/events/MotionEventHandlerTest.java
Another try...
Implemented delayed motion events without timers, as you suggested.
`updateMotionState` looks complex only because I combined in one update (with new position) and correct (without position).
Positions-Events flow become not linear, because of that we need update events directly and some modifications.
More comments in code...
=> Implement motion detection similar to trips detection

src/org/traccar/Context.java, src/org/traccar/events/MotionEventHandler.java, src/org/traccar/reports/model/TripsConfig.java, test/org/traccar/events/MotionEventHandlerTest.java, test/org/traccar/reports/ReportUtilsTest.java
Here is the implementation of additional stop detection by ignition.
In case devices always report `ignition = false` made this function switchable.
=> Correct stop state by ignition.

src/org/traccar/database/DataManager.java, src/org/traccar/model/User.java
Trim email field on user create/update.
On login trim input and force to lowercase as is standard with most sites.
=> Trim email field on auth

swagger.json
Saved Commands added and units removed
=> Update swagger documentation to recent changes

src/org/traccar/BasePipelineFactory.java, src/org/traccar/Context.java, src/org/traccar/events/FuelDropEventHandler.java, src/org/traccar/events/MotionEventHandler.java, src/org/traccar/reports/ReportUtils.java, src/org/traccar/reports/Stops.java, src/org/traccar/reports/Trips.java, src/org/traccar/reports/model/TripsConfig.java, test/org/traccar/events/MotionEventHandlerTest.java, test/org/traccar/reports/ReportUtilsTest.java
fix #3539 
Also removed check for valid from `FuelDropEventHandler`
=> Make check for valid in MotionEventHandler optional

src/org/traccar/model/CellTower.java, src/org/traccar/model/Position.java, src/org/traccar/protocol/TeltonikaProtocolDecoder.java, test/org/traccar/ProtocolTest.java, test/org/traccar/protocol/TeltonikaProtocolDecoderTest.java
Improved IO values decoding according to #3544 
Added a couple of tests from FMB920
=> Improve Teltonika IO decoding

src/org/traccar/protocol/XexunProtocolDecoder.java
A proposed change to allow for the correct use of value.toLowerCase() handling (case-insensitive switch statement functionality.
=> Update case statement Xexun Protocol

src/org/traccar/api/resource/CommandResource.java, src/org/traccar/database/CommandsManager.java, src/org/traccar/database/ConnectionManager.java, swagger.json
- If device is not online commands put in by device queues
- When device becomes online again traccar send all queued commands.
Queues are in memory only, lost if server restarted.
=> Implement buffered/delayed commands

setup/default.xml, src/org/traccar/Context.java, src/org/traccar/database/DataManager.java, src/org/traccar/database/LdapProvider.java
Made it much more flexible.
- Implemented the way with service login and pre lookup user in catalog.
- Fill user fields from catalog
- Added switch to disable internal login (users are still in DB)
- Allow to make user admin if he is in predefined group (on creation stage)
=> Improve LDAP

src/org/traccar/database/DataManager.java, src/org/traccar/database/PermissionsManager.java
Fixed couple of issues:
- Fix local login if ldap enabled
- Do not allow user edit own "Limit Command" permission. Missed this check on backend side.
=> - Fix local login if ldap enabled & Limit Command permission

src/org/traccar/protocol/Pt502ProtocolDecoder.java, test/org/traccar/protocol/Pt502ProtocolDecoderTest.java
Although this alarm is not sent always in this way, I have received some
messages with this format
=> handle cut power alarm for pt502

src/org/traccar/notification/NotificationMail.java, src/org/traccar/notification/PropertiesProvider.java
Handle "boolean" and "string as boolean" attributes in mail configuration
fix #3679
=> Handle boolean parameters in mail configuration attributes

schema/changelog-3.16.xml, schema/changelog-master.xml, src/org/traccar/BaseProtocolDecoder.java, src/org/traccar/api/resource/DeviceResource.java, src/org/traccar/database/DeviceManager.java, src/org/traccar/database/PermissionsManager.java, src/org/traccar/model/Device.java
Here is simple implementation of device disabling. In continue of https://github.com/tananaev/traccar/pull/3697
Device is basically hidden from all users except admins.
Incoming positions might be stored or not in DB. (`database.storeDisabled`)
=> Implement device disable (simple)

schema/changelog-3.16.xml, src/org/traccar/model/Server.java, src/org/traccar/model/User.java
Added field to store POI layer URL.
Made `VARCHAR` length as for `mapUrl`
fix #3714 
fix #513
=> Add poiLayer field to User/Server model

src/org/traccar/FilterHandler.java
https://www.traccar.org/forums/topic/does-filterduplicate-and-filterskiplimit-works-well-for-gt06-protocol/
=> Adding filter.skipLimit functionality based on Server Time Only

src/org/traccar/api/BaseObjectResource.java, src/org/traccar/model/Device.java, src/org/traccar/model/GroupedModel.java
Fix https://github.com/tananaev/traccar/pull/3736#issuecomment-360967138
And implemented check for `groupId` for Devices and Groups in the same way.
=> Fix ScheduledModel objects permission check

setup/default.xml, src/org/traccar/protocol/OpenGtsProtocol.java, src/org/traccar/protocol/OpenGtsProtocolDecoder.java, test/org/traccar/protocol/OpenGtsProtocolDecoderTest.java
Signed-off-by: Kostiantyn Luzan <vblack2006@gmail.com>
=> Add support for OpenGTS compatible clients (GPSLogger for Android)

src/org/traccar/geofence/GeofenceCircle.java
This method is used in my mqtt integration with traccar which is being refactored to be published
=> method to calculate distance from center of circle

src/org/traccar/model/User.java
"-" should be a safe symbol and UDID in Xcode includes them
=> allow - in token to use UDID from Xcode as token

src/org/traccar/protocol/Gps103ProtocolDecoder.java
Sorry, of course this way is better.
=> Use parser more correctly

src/org/traccar/protocol/WialonProtocol.java, src/org/traccar/protocol/WialonProtocolDecoder.java, src/org/traccar/protocol/WondexFrameDecoder.java, src/org/traccar/protocol/WondexProtocol.java, src/org/traccar/protocol/WondexProtocolDecoder.java
Migrated Wialon and Wondex.
Also want to test with real wondex device tomorrow.
=> Migrate Wialon and Wondex

src/org/traccar/protocol/Gl200BinaryProtocolDecoder.java, src/org/traccar/protocol/Gl200FrameDecoder.java, src/org/traccar/protocol/Gl200Protocol.java, src/org/traccar/protocol/Gl200ProtocolDecoder.java, src/org/traccar/protocol/Gl200TextProtocolDecoder.java, src/org/traccar/protocol/TeltonikaFrameDecoder.java, src/org/traccar/protocol/TeltonikaProtocol.java, src/org/traccar/protocol/TeltonikaProtocolDecoder.java, src/org/traccar/protocol/TeltonikaProtocolEncoder.java
Here is the rest of protocols picked by me
=> Migrate gl200 and teltonika to netty 4

src/org/traccar/helper/BufferUtil.java, src/org/traccar/protocol/AtrackFrameDecoder.java, src/org/traccar/protocol/EnforaProtocolDecoder.java, src/org/traccar/protocol/WatchFrameDecoder.java, src/org/traccar/protocol/WatchProtocol.java, src/org/traccar/protocol/WatchProtocolDecoder.java, src/org/traccar/protocol/WatchProtocolEncoder.java, src/org/traccar/protocol/WondexFrameDecoder.java, src/org/traccar/protocol/XexunFrameDecoder.java, src/org/traccar/protocol/XexunProtocol.java, src/org/traccar/protocol/XexunProtocolDecoder.java, src/org/traccar/protocol/XirgoProtocol.java, src/org/traccar/protocol/XirgoProtocolDecoder.java, src/org/traccar/protocol/Xt013Protocol.java, src/org/traccar/protocol/Xt013ProtocolDecoder.java, src/org/traccar/protocol/Xt2400Protocol.java, src/org/traccar/protocol/Xt2400ProtocolDecoder.java, src/org/traccar/protocol/YwtProtocol.java, src/org/traccar/protocol/YwtProtocolDecoder.java
Migrated protocols
Added `BufferUtil` helper class.
=> Migrate Y, X, W protocols

src/org/traccar/protocol/UlbotechFrameDecoder.java, src/org/traccar/protocol/UlbotechProtocol.java, src/org/traccar/protocol/UlbotechProtocolDecoder.java, src/org/traccar/protocol/UproProtocol.java, src/org/traccar/protocol/UproProtocolDecoder.java, src/org/traccar/protocol/V680Protocol.java, src/org/traccar/protocol/V680ProtocolDecoder.java, src/org/traccar/protocol/VisiontekProtocol.java, src/org/traccar/protocol/VisiontekProtocolDecoder.java, src/org/traccar/protocol/Vt200FrameDecoder.java, src/org/traccar/protocol/Vt200Protocol.java, src/org/traccar/protocol/Vt200ProtocolDecoder.java, src/org/traccar/protocol/VtfmsFrameDecoder.java, src/org/traccar/protocol/VtfmsProtocol.java, src/org/traccar/protocol/VtfmsProtocolDecoder.java
Unfortunately small amount today
=> Migrate U,V protocols

src/org/traccar/protocol/LaipacProtocolDecoder.java
Added validation of other statuses
- R: repeating the message when the package was not received
- P: send when GPS receiver didn't move but there is a valid location avaible)
=> Added validation of other statuses

src/org/traccar/protocol/TeltonikaProtocolDecoder.java
https://github.com/traccar/traccar/issues/3973
=> Added gps status

src/org/traccar/notification/MessageException.java, src/org/traccar/sms/SmsGatewayClient.java
Implemented integration with SMS provider SmsGateway.me
Configuration parameters required:
```xml
<entry key="sms.smsgateway.token">[Hidden]</entry>
<entry key="sms.smsgateway.deviceId">[Hidden]</entry>
```
These parameters are provided after registering on SmsGateway.me
=> Integration with SmsGateway.me

src/org/traccar/api/resource/DeviceResource.java, src/org/traccar/database/DeviceManager.java, src/org/traccar/helper/LogAction.java, src/org/traccar/model/DeviceAccumulators.java
Implemented resetting device engine hours with total distance
https://www.traccar.org/forums/topic/adjust-hours-and-service/
=> Implement Device Engine Hours reset

README.md
=> Remove redundant words from README

src/org/traccar/protocol/OwnTracksProtocolDecoder.java
- Stricter content checks
- Event creation
- Device status handling
- Additional attributes
see [message description](http://owntracks.org/booklet/tech/json/#_typelocation)
=> Owntracks Protocol for Traccar 4.2

src/org/traccar/protocol/GalileoProtocolDecoder.java
Galileo sends power values in mV
=> Fix Galileo power units

src/org/traccar/helper/Log.java, src/org/traccar/model/Command.java, src/org/traccar/protocol/WatchProtocol.java, src/org/traccar/protocol/WatchProtocolEncoder.java, test/org/traccar/protocol/WatchProtocolEncoderTest.java
protocol documentation: https://github.com/tananaev/traccar/files/213814/3g.elec.comm.protocol.docx
=> Send message (that is displayed on the watch's display)

src/org/traccar/protocol/WatchProtocolEncoder.java, test/org/traccar/protocol/WatchProtocolEncoderTest.java
without this the received message is displayed as gibrish
=> fixed message encoding

src/org/traccar/Context.java, src/org/traccar/protocol/WatchFrameDecoder.java, src/org/traccar/protocol/WatchProtocol.java, src/org/traccar/protocol/WatchProtocolDecoder.java, src/org/traccar/protocol/WatchProtocolEncoder.java, test/org/traccar/BaseTest.java, test/org/traccar/ProtocolTest.java, test/org/traccar/protocol/WatchFrameDecoderTest.java, test/org/traccar/protocol/WatchProtocolDecoderTest.java, test/org/traccar/protocol/WatchProtocolEncoderTest.java
This is the smallest patch I could create that still works. If either one of the 2 places doesn't use ISO_8859_1 then the watch either doesn't even get the voice message or it gets gibrish.
This was tested with Q50 watch.
=> fixed 8bit voice message

src/main/java/org/traccar/protocol/XexunProtocolDecoder.java
done right this time!
sorry I just had a github crash course!
=> updated "help me" option for xexun protocol

src/main/java/org/traccar/notification/NotificatorManager.java, src/main/java/org/traccar/notificators/NotificatorTelegram.java
Hi, 
as discussed in #4274 I added Telegram notification support.
=> Added Telegram support

src/main/java/org/traccar/BasePipelineFactory.java
Solve "Hours Accumulator" not adding hours because of order in Handler init.
=> "Hours Accumulator" not adding hours

src/main/java/org/traccar/model/Position.java, src/main/java/org/traccar/protocol/Gt06ProtocolDecoder.java
=> support gt06 extend Protocol

src/main/java/org/traccar/BaseProtocolEncoder.java, src/main/java/org/traccar/database/DeviceManager.java, src/main/java/org/traccar/database/IdentityManager.java, src/main/java/org/traccar/protocol/LaipacProtocol.java, src/main/java/org/traccar/protocol/LaipacProtocolDecoder.java, src/main/java/org/traccar/protocol/LaipacProtocolEncoder.java, src/test/java/org/traccar/TestIdentityManager.java, src/test/java/org/traccar/protocol/LaipacProtocolDecoderTest.java
Enhance Laipac protocol decoder and encoder
=> Enhance Laipac protocol decoder and encoder

src/main/java/org/traccar/BaseProtocolEncoder.java, src/main/java/org/traccar/database/DeviceManager.java, src/main/java/org/traccar/database/IdentityManager.java, src/main/java/org/traccar/protocol/Gt06ProtocolEncoder.java, src/main/java/org/traccar/protocol/H02ProtocolEncoder.java, src/main/java/org/traccar/protocol/HuabaoProtocolEncoder.java, src/main/java/org/traccar/protocol/LaipacProtocolDecoder.java, src/main/java/org/traccar/protocol/MeitrackProtocolEncoder.java, src/main/java/org/traccar/protocol/Tk103ProtocolEncoder.java, src/test/java/org/traccar/TestIdentityManager.java
=> Make device password a group configurable attribute

src/main/java/org/traccar/BaseProtocolDecoder.java
=> Make session cache per protocol configurable

src/main/java/org/traccar/protocol/WatchProtocolDecoder.java, src/test/java/org/traccar/protocol/WatchProtocolDecoderTest.java
fix the Watch Protocol Heart Rate & Blood Pressure Report
=> watch protocol case fix

src/main/java/org/traccar/protocol/DmtProtocolDecoder.java
Added support for running time and odometer. 
They have a number of devices that track them, we use the G62's to track equipment hours.
=> Update DMT protocol to support Run Hours & Odometer

src/main/java/org/traccar/config/Keys.java, src/main/java/org/traccar/web/WebServer.java
This needs configuration. Just making the PR to get some guidance.
=> adding jetty log

src/main/java/org/traccar/web/GpxBuilder.java
correct gpx file opening in some softwares
=> change element from <geoidheight> to <ele>

swagger.json
Fix for #4559 
Signed-off-by: Syed Mujeer Hashmi <mujeerhashmi@4csolutions.in>
=> swagger: Add missing 'phone' field in User model

src/main/java/org/traccar/BasePipelineFactory.java, src/main/java/org/traccar/BaseProtocolDecoder.java, src/main/java/org/traccar/WebDataHandler.java, src/main/java/org/traccar/WindowsService.java, src/main/java/org/traccar/WrapperInboundHandler.java, src/main/java/org/traccar/WrapperOutboundHandler.java, src/main/java/org/traccar/api/AsyncSocket.java, src/main/java/org/traccar/api/BaseObjectResource.java, src/main/java/org/traccar/api/UserPrincipal.java, src/main/java/org/traccar/api/resource/DeviceResource.java, src/main/java/org/traccar/api/resource/UserResource.java, src/main/java/org/traccar/database/BaseObjectManager.java, src/main/java/org/traccar/database/CommandsManager.java, src/main/java/org/traccar/database/DataManager.java, src/main/java/org/traccar/database/DeviceManager.java, src/main/java/org/traccar/database/PermissionsManager.java, src/main/java/org/traccar/database/QueryBuilder.java, src/main/java/org/traccar/geofence/GeofenceCircle.java, src/main/java/org/traccar/helper/BitBuffer.java, src/main/java/org/traccar/helper/Checksum.java, src/main/java/org/traccar/helper/DateBuilder.java, src/main/java/org/traccar/helper/Parser.java, src/main/java/org/traccar/protocol/OwnTracksProtocolDecoder.java, src/main/java/org/traccar/reports/ReportUtils.java
- Remove unused/unnecessary code
- Convert some classes to lambdas
- Make property declarations final
- Other misc improvements
=> Various minor code cleanup

src/main/java/org/traccar/reports/ReportUtils.java
Fixing distance calculation condition
=> Fixing distance calculation condition

src/main/java/org/traccar/MainModule.java, src/main/java/org/traccar/geocoder/MapboxGeocoder.java, src/test/java/org/traccar/geocoder/GeocoderTest.java
Add Mapbox reverser geocoder support
=> Implements MapboxGeocoder

setup/default.xml, src/main/java/org/traccar/protocol/Mavlink2Protocol.java, src/main/java/org/traccar/protocol/Mavlink2ProtocolDecoder.java, src/test/java/org/traccar/protocol/Mavlink2ProtocolDecoderTest.java
Mavlink2 is a common protocol for unmanned vehicles and flight controllers like Pixhawk devices.
=> Add mavlink2 protocol support

src/main/java/org/traccar/protocol/MictrackProtocolDecoder.java
Support Type value for MicTrack protocol Helps identify the current mode of data received.
=> Support for Type - MicTrack

src/main/java/org/traccar/notificators/NotificatorTelegram.java
Add chatId based on "notificationTelegramChatId" user attributes, if available.
According to https://github.com/traccar/traccar/pull/4309
=> Modify NotificatorTelegram.java

src/main/java/org/traccar/database/PermissionsManager.java
Race condition during API requests concerning devices (e.g. positions, trips) occasionally causes the check if a user has access to a device to fail, requiring admin or manager access, the request fails with a 400 "manager access required".
Tested by adding a Thread.sleep() between the cache clear() and re-population from the database, in refreshDeviceAndGroupPermissions(), and then running a script to exercise the API. First an update to a device, causing refreshDeviceAndGroupPermissions() to be called and then numerous requests reading device, positions and trips. All these call checkDevice(). During the first thread’s sleep the requests failed with 400 manager access required.
Fix was to make access to the device/user permissions cache thread safe. Test results confirm the read …
=> Make access to permissions cache thread-safe

src/main/java/org/traccar/geocoder/HereGeocoder.java
fix bug in here geocoder formatted address
=> fix bug in here geocoder formatted address

src/main/java/org/traccar/geolocation/OpenCellIdGeolocationProvider.java
Add error message received from OpenCellId geolocation provider
=> Improve OpenCellId error logging

src/main/java/org/traccar/protocol/TotemProtocol.java, src/main/java/org/traccar/protocol/TotemProtocolEncoder.java
Added some basic commands that I needed for Totem - willing to extend it to full available list down the line. 
But wanted to open this PR and ask if there is a way to handle SMS and GPRS commands? And which Protocol implements that - as I checked some popular ones and did not find any. Would like to implement either sending via SMS or via GPRS, but need some help/example on how this is handled elsewhere. Thanks!
=> Totem - add some basic commands

templates/full/passwordReset.vm
Adds the reset-password endpoint to the reset link.
=> Fixes passwordReset.vm template

src/main/java/org/traccar/helper/NMEA.java, src/main/java/org/traccar/protocol/PiligrimProtocolDecoder.java
This branch adds basic support for protocol used by Piligrim M-5000/M-10000 and probably some other devices.
=> Support for Piligrim M-5000/M-10000 protocol

src/main/java/org/traccar/protocol/WialonProtocolDecoder.java, src/test/java/org/traccar/protocol/WialonProtocolDecoderTest.java
Pull request as discussed [here](https://www.traccar.org/forums/topic/motion-attribute-using-wialon-protocol/#post-81534).
=> Better handling of attributes (boolean attributes + setAccuracy special case) for Wialon protocol

setup/default.xml, src/main/java/org/traccar/config/Keys.java, src/main/java/org/traccar/session/ConnectionManager.java
RegisterUnknown filter with regex #5023
=> RegisterUnknown filter with regex

src/main/java/org/traccar/api/resource/PositionResource.java, swagger.json
Add DELETE endpoint for Positions based on time span.
closes #4387
=> Add DELETE api endpoint for Positions

src/main/java/org/traccar/MainModule.java, src/main/java/org/traccar/api/resource/SessionResource.java, src/main/java/org/traccar/config/Keys.java, src/main/java/org/traccar/database/OpenIdProvider.java, src/main/java/org/traccar/helper/WebHelper.java, src/test/java/org/traccar/helper/WebHelperTest.java
Implements auto endpoint discovery and the ability to restrict access to groups.
Discussion in #5057
=> Updates to OpenID Implementation

src/main/java/org/traccar/model/Position.java, src/main/java/org/traccar/protocol/TeltonikaProtocolDecoder.java
Addition of Teltonika decode FMBXXX IO30 fault count, updated modern web pull request will be sent shortly.
=> Teltonika IO30 Fault count

src/main/java/org/traccar/protocol/HuabaoProtocolDecoder.java
Added support for VL502 additional alarms, Protocol document Page 44, 0x03
[Communication Protocol of VL502  V1.0.7_eng.pdf](https://github.com/traccar/traccar/files/11443290/Communication.Protocol.of.VL502.V1.0.7_eng.pdf)
=> Add VL502 Alarms

src/main/java/org/traccar/broadcast/RedisBroadcastService.java
@tananaev please have a look in this small fix (mistake)
=> Redis broadcast fix

src/main/java/org/traccar/protocol/TeltonikaProtocolDecoder.java
Small fix for #5129 thought traccar expects value in kilometer.
=> Update wrong odometer value

src/main/java/org/traccar/web/WebServer.java
Fixes https://github.com/traccar/traccar/issues/5138
=> Set session cookie max age if web.sessionTimeout is set

src/main/java/org/traccar/model/Command.java, src/main/java/org/traccar/protocol/GatorProtocol.java, src/main/java/org/traccar/protocol/GatorProtocolDecoder.java, src/main/java/org/traccar/protocol/GatorProtocolEncoder.java, src/test/java/org/traccar/protocol/GatorProtocolEncoderTest.java
**Functionalities Added for Gator protocol**
- DeviceId/IMEI Encoding (Tested)
- Rollback packet encoding (Tested)
- Calibration packet calculation
resolves #5140
=> Add rollback command for Gator

src/main/java/org/traccar/protocol/WatchProtocolDecoder.java, src/test/java/org/traccar/protocol/WatchProtocolDecoderTest.java
- fix the position pattern for the Watch Protocol to handle an empty latitude mark
- handle blood oxygen data
=> Watch Protocol Decoder update

src/main/java/org/traccar/protocol/NavtelecomProtocolDecoder.java
- before "case 5" delete blank line;
- field 15 conversion to meters;
- fields 53, 66 (check 15 bit, value 0-14 bits);
- field 54 check negative, conversion to liters;
- field 57 conversion to meters;
- fields 207-255 fix field num check (I didn't compare the index correctly)
=> fix PR #4839:

src/main/java/org/traccar/protocol/StartekProtocolDecoder.java
Update to add more decoder Alarm for Startek Protocol (StartekProtocolDecoder.java)
ALARM_LOW_POWER
ALARM_POWER_CUT
ALARM_POWER_RESTORED
Please review. thank you.
=> Update decoder Alarm for "StartekProtocolDecoder.java"

src/main/java/org/traccar/protocol/UproProtocolDecoder.java, src/test/java/org/traccar/protocol/UproProtocolDecoderTest.java
With reference to the protocol, 'd' represents the analog input voltage
=> analog input voltage decode

src/main/java/org/traccar/protocol/Gl200TextProtocolDecoder.java, src/test/java/org/traccar/protocol/Gl200TextProtocolDecoderTest.java
include iccid
[GV310LAU @Track Air Interface Protocol V2.02.pdf](https://github.com/traccar/traccar/files/14797521/GV310LAU.%40Track.Air.Interface.Protocol.V2.02.pdf)
=> Fix INF message on GV310LAU

src/main/java/org/traccar/handler/FilterHandler.java
check time > 0 in speed filter
=> Speed calculation is not correct when the device sends 2 positions in the same second.

src/main/java/org/traccar/forward/PositionForwarderMqtt.java
It should publish positionData instead of topic element
=> Wrong data published in MQTT (PositionForwarderMqtt)

src/main/java/org/traccar/MainModule.java, src/main/java/org/traccar/geocoder/GoogleGeocoder.java, src/test/java/org/traccar/geocoder/GeocoderTest.java
We have integrated Ola Maps geocoder. Kindly review.
=> geocoder: Implement OlaMaps Reverse geocoder

src/main/java/org/traccar/protocol/RstProtocolDecoder.java
adjustes firmware regex length to allow reading most recent firmwares.
=> Fix RST V10.02 firmware version compatibility

src/main/java/org/traccar/sms/HttpSmsClient.java
https://github.com/traccar/traccar/issues/5402
=> remove trim on sms body

src/main/java/org/traccar/api/resource/UserResource.java
Managers should also be allowed to see wich of their users are linked to devices, since they can have many users bellow them to manage.
[Corresponding web app change](https://github.com/traccar/traccar-web/pull/1270).
=> Allow managers to see device's users

src/main/java/org/traccar/protocol/HuabaoProtocolDecoder.java
With this we can then make some computed attributes to get the rest of the data.
From the comment on the code looks like this is always the data type, I only have the documentation for aovx.
https://github.com/AOVX-Corporation/AOVX_Share/blob/main/Document/en/01_G%20series/AOVX_G%26A_Series%20Cloud%20Platform%20Protocol.pdf
=> add data type in huabao (aovx)

src/main/java/org/traccar/MainModule.java, src/main/java/org/traccar/forward/PositionForwarderWialon.java
PositionForwarderWialon seems pretty good and i have no idea why this doesn't described in configuration docs.
But this missing important attributes, so now forwarder looks well.
Test on Wialon:
=> Add attributes to Wialon forwarder

src/main/java/org/traccar/api/BaseObjectResource.java, src/main/java/org/traccar/api/ExtendedObjectResource.java, src/main/java/org/traccar/api/SimpleObjectResource.java, src/main/java/org/traccar/api/resource/AttributeResource.java, src/main/java/org/traccar/api/resource/CalendarResource.java, src/main/java/org/traccar/api/resource/CommandResource.java, src/main/java/org/traccar/api/resource/DeviceResource.java, src/main/java/org/traccar/api/resource/DriverResource.java, src/main/java/org/traccar/api/resource/GeofenceResource.java, src/main/java/org/traccar/api/resource/GroupResource.java, src/main/java/org/traccar/api/resource/MaintenanceResource.java, src/main/java/org/traccar/api/resource/NotificationResource.java, src/main/java/org/traccar/api/resource/OrderResource.java, src/main/java/org/traccar/api/resource/ReportResource.java, src/main/java/org/traccar/api/resource/UserResource.java
This implementation adds sorting functionality, allowing sorting by name or description. I used reflection to determine which of the two fields should be used for sorting, but I’m not sure if this may interfere with performance. If performance is affected, I can pass the sorting field as a parameter in the URL and add it only to the LinkFields in Traccar Web, where it's most needed. I appreciate your review of this approach.
This implementation is based on the discussion in [traccar/traccar-web#1289](https://github.com/traccar/traccar-web/pull/1289).
=> Implement Sorting Functionality

src/main/java/org/traccar/protocol/Gt06ProtocolDecoder.java, src/test/java/org/traccar/protocol/Gt06ProtocolDecoderTest.java
[NT11 NT20 NT26 NT40 NT46 Protocol rev3.33.pdf](https://github.com/user-attachments/files/18044962/NT11.NT20.NT26.NT40.NT46.Protocol.rev3.33.pdf)
=> X3Tech NT20 new location message

src/main/java/org/traccar/protocol/Gl200TextProtocolDecoder.java, src/test/java/org/traccar/protocol/Gl200TextProtocolDecoderTest.java
[GV355CEU@Track_Air_Interface_Protocol_v0704.pdf](https://github.com/user-attachments/files/18134033/GV355CEU%40Track_Air_Interface_Protocol_v0704.pdf)
=> Fix GTCAN in GV355CEU

src/main/java/org/traccar/handler/events/FuelEventHandler.java, templates/full/deviceFuelDrop.vm, templates/full/deviceFuelIncrease.vm
Added quantity of fuel drop/increase in email notification
=> Add quantity of fuel drop/increase in notification

src/main/java/org/traccar/config/Keys.java, src/main/java/org/traccar/database/OpenIdProvider.java
Some OIDC providers don't have "groups" claim in id token, but have "roles". With this setting in traccar.xml there is ability to change it to work properly.
Example is
` <entry key='openid.groupsClaimName'>roles</entry>`
I didn't find how to add new commits to PR so opened new one
=> Add custom group claim

src/test/java/org/traccar/ProtocolTest.java
Added network to the list of attributes to verify in tests
Unlocks #5502
=> ProtocolTest - network attribute verification

src/main/java/org/traccar/handler/ComputedAttributesHandler.java, src/main/java/org/traccar/model/ExtendedModel.java, src/main/java/org/traccar/notificators/NotificatorFirebase.java, src/main/java/org/traccar/notificators/NotificatorTraccar.java, src/main/java/org/traccar/protocol/RuptelaProtocolDecoder.java, src/main/java/org/traccar/protocol/TeltonikaProtocolDecoder.java
Introduced the `removeAttribute` and `remove<Type>` methods and replaced all the existing instances of the attribute removal.
Unlocks #5502
=> ExtendedModel refactor

src/main/java/org/traccar/protocol/MobilogixProtocol.java, src/main/java/org/traccar/protocol/MobilogixProtocolEncoder.java, src/test/java/org/traccar/protocol/MobilogixProtocolEncoderTest.java
[EI_2021_0018__MOBILOGIX__MT2000_PROTOCOL_OVER_THE_AIR__19_08_2021__V1_3_7.pdf](https://github.com/user-attachments/files/18919508/EI_2021_0018__MOBILOGIX__MT2000_PROTOCOL_OVER_THE_AIR__19_08_2021__V1_3_7.pdf)
=> Implement mobilogix commands

src/main/java/org/traccar/protocol/Minifinder2ProtocolDecoder.java
Add Alarm attribute to the Minifinder2 protocol to get the raw alarm data.
=> Add Alarm attribute to Minifinder2ProtocolDecoder.java

src/main/java/org/traccar/model/Position.java, src/main/java/org/traccar/protocol/AplicomProtocolDecoder.java, src/main/java/org/traccar/protocol/SnapperProtocolDecoder.java, src/main/java/org/traccar/protocol/TeltonikaProtocolDecoder.java
https://github.com/traccar/traccar-web/pull/1343
=> Create engineTemp known attribute

src/main/java/org/traccar/protocol/TeltonikaProtocol.java, src/main/java/org/traccar/protocol/TeltonikaProtocolDecoder.java, src/main/java/org/traccar/protocol/TeltonikaProtocolEncoder.java
- Engine stop / resume commands
- Engine load, milDistance, hybridBatteryPackLevel and RPM
https://wiki.teltonika-gps.com/view/FMB003_Teltonika_Data_Sending_Parameters_ID
=> Update teltonika protocol

src/main/java/org/traccar/protocol/HuabaoProtocolDecoder.java, src/test/java/org/traccar/protocol/HuabaoProtocolDecoderTest.java
https://www.getscale.com.br/gs-404
[GS404_protocolo.pdf](https://github.com/user-attachments/files/19676439/GS404_protocolo.pdf)
[V_Series Protocol.pdf](https://github.com/user-attachments/files/19676449/V_Series.Protocol.pdf)
=> Implement Getscale RFID reader with AOVX

src/main/java/org/traccar/protocol/CellocatorProtocolEncoder.java
This PR is part of a series of 2 which is a demand by our University Professor, which one of the tasks is to use a Software called Spotbugs to find bugs in a repository and create PRs to "fix" them. 
I've choose two bugs that in my limited vision do not inflict in a major fix.
=> fix: wrong add priority spotbugs findbugs 75QUA 1/2

src/main/java/org/traccar/helper/Checksum.java
This PR is part of a series of 2 which is a demand by our University Professor, which one of the tasks is to use a Software called Spotbugs to find bugs in a repository and create PRs to "fix" them.
I've choose two bugs that in my limited vision do not inflict in a major fix.
=> fix: bug bit signedcheck high bit spotbugs 75QUA 2/2

templates/notifications/it/alarm.vm, templates/notifications/it/commandResult.vm, templates/notifications/it/deviceExpiration.vm, templates/notifications/it/deviceExpirationReminder.vm, templates/notifications/it/deviceFuelDrop.vm, templates/notifications/it/deviceFuelIncrease.vm, templates/notifications/it/deviceInactive.vm, templates/notifications/it/deviceMoving.vm, templates/notifications/it/deviceOffline.vm, templates/notifications/it/deviceOnline.vm, templates/notifications/it/deviceOverspeed.vm, templates/notifications/it/deviceStopped.vm, templates/notifications/it/deviceUnknown.vm, templates/notifications/it/driverChanged.vm, templates/notifications/it/geofenceEnter.vm, templates/notifications/it/geofenceExit.vm, templates/notifications/it/ignitionOff.vm, templates/notifications/it/ignitionOn.vm, templates/notifications/it/maintenance.vm, templates/notifications/it/media.vm, templates/notifications/it/passwordReset.vm, templates/notifications/it/queuedCommandSent.vm, templates/notifications/it/scheduledReport.vm, templates/notifications/it/userExpiration.vm, templates/notifications/it/userExpirationReminder.vm
=> Add Italian language Files
